### ISSUE TITLE
[UI] UI change for Edit Page

### ISSUE THREAD

**Issue by Vignesh025** [VigneshDevHub/CampX#1]
**Description**
Improve the UI of Edit Campground page to be more attractive.

**Current Behavior**
The current UI is minimalist.

*If you're going to work on this issue, create a new issue explaining your changes and mention this issue.*

**Comment by BinaryBhakti** [comment]
I want to work on this issue. Please assign this issue to me.

**Comment by Vignesh025** [comment]
Hey @BinaryBhakti , Create a new issue stating all the changes you want to make and mention this issue like (issue#1). I'll review it and assign it to you.

**Comment by BinaryBhakti** [comment]
Is this the working space for this issue? 
https://campx-f9sv.onrender.com/campgrounds  Also I wanted to know if you have any pre-thought idea, so that I can align myself to the same or else I can work in the best possible way according to me.

**Comment by Vignesh025** [comment]
Hi @BinaryBhakti  ,

No, that's not the page you need to work on. Instead, try creating a new real-time campground on the website. After creating the campground, if you view it, you'll see an edit button (if you are the author of that campground). When you press the edit button, it will take you to the edit page.

I’d like to focus on changing the UI of that edit page. While I don’t have any specific ideas in mind for the new UI, please ensure that the design aligns with the overall look and feel of the project.

Thanks, and looking forward to your approach!

**Comment by BinaryBhakti** [comment]
https://campx-f9sv.onrender.com/campgrounds/new

I find this one, so is this the working space or once I create a new campground, after that when I want to edit my campground that  is the page which I have to work on.

If that's the working space then can I create a new campground and then check the edit page of that, to get a better understanding.

**Comment by BinaryBhakti** [comment]
![image](https://github.com/user-attachments/assets/f8f73a5d-29f5-4e4c-b7d1-e2044cd1d67b)
https://campx-f9sv.onrender.com/campgrounds/66f7cad0d7ef5f28428f2c23/edit

I guess this is the working space.

**Comment by Vignesh025** [comment]
Yes, that is correct. This is indeed the working space.
