### ISSUE TITLE
[BUG] No space below login 

### ISSUE THREAD

**Issue by leonyangela** [VigneshDevHub/CampX#101]
**Describe the bug**
I have noticed that there is no space below the login box when an alert message is displayed. This results in a cramped appearance and affects the overall user experience. I would like to fix it, could you please assign it to me? Thanks

**To Reproduce**
1. Go to /campgrounds
2. Click on "New Campground" Navbar
3. Scroll down to bottom

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/f81b12af-fe89-4938-9b52-d361c8274610)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: 129.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Vignesh025** [comment]
Hey @leonyangela ,
Someone else is currently working on the UI of the login page. Feel free to explore other areas of the project and raise any new issues!
