### ISSUE TITLE
[FEATURE] Adding scroll to top button

### ISSUE THREAD

**Issue by Durga-prasad-1** [VigneshDevHub/CampX#103]
**Is your feature request related to a problem? Please describe.**
When navigating downward in campgrounds page, it becomes cumbersome to scroll back to the top manually, especially on mobile devices. This impacts user experience, making it harder to navigate.

**Describe the solution you'd like**
I would like to add a "Scroll to Top" button that appears after the user has scrolled down a certain amount. Clicking this button will smoothly scroll the page back to the top.

**Describe alternatives you've considered**
An alternative could be adding a fixed "Back to Top" link in the footer, though a floating button provides a better user experience across devices.

**Comment by Durga-prasad-1** [comment]
can you please add hacktoberfest label

**Comment by Vignesh025** [comment]
Hey @Durga-prasad-1 , Someone is already working on this issue. I'll check whether they're still working on it and let you know.

**Comment by Durga-prasad-1** [comment]
i will be waiting for your response

**Comment by Vignesh025** [comment]
@Durga-prasad-1 , You can proceed. I'm assigning this to you!
