### ISSUE TITLE
[UI] Navbar can be visually optimized

### ISSUE THREAD

**Issue by sanjesh17** [VigneshDevHub/CampX#107]
**Description**
The navbar can be worked on a little bit, as it looks odd and kind of old.

**Current Behavior**
The navbar has uneven padding of elements and seems to be outdated

**Proposed Behavior**
Padding could be normalized and the navbar size could be increase and blur effect could be added for additional visual optimization

**Comment by Vignesh025** [comment]
Hey, someone is already working on the navbar, Please feel free to explore the project and create any new issues.
