### ISSUE TITLE
[UI] Various UI enhancements

### ISSUE THREAD

**Issue by Sneharaj7645653** [VigneshDevHub/CampX#11]
The UI of the home page needs improvement.
- [x] The name of the website, CampX, lacks appeal. Adding some animation could enhance its attractiveness.
- [ ] Make the home page responsive.
- [ ] The orientation of the elements in the nav bar should be improved for a better user experience.
- [ ] The background appears dull and ashen. Given that the website is dedicated to adventure and travel, incorporating vibrant colours could significantly enhance its visual appeal.
- [ ] Consider replacing "CampX" at the centre with a compelling quote related to travel and adventure.
- [ ] The footer needs to be made more prominent to leave a lasting impression.

**Comment by Vignesh025** [comment]
@Sneharaj7645653  you can proceed, I'm assigning this to you.

**Comment by Sneharaj7645653** [comment]
Sure

**Comment by Vignesh025** [comment]
Hi @Sneharaj7645653, are you currently working on any other changes? Just checking because someone else is interested in working on improving the homepage UI. Let me know!

**Comment by Sneharaj7645653** [comment]
Hello @Vignesh025,

I am currently working on improving the Home Page, and it appears that others are also interested in this. Please feel free to take the lead on the call as it's always beneficial to have more contributors. However, I will continue contributing and raising the pull request as planned, even if the issue has been assigned to a more experienced contributor.

Thank you for your understanding.

**Comment by Vignesh025** [comment]
Thank you for letting me know, but I can't have more than one person working on the same page, as it will become cumbersome to manage. I just wanted to confirm if you're continuing with the work so I can inform others.

**Comment by Sneharaj7645653** [comment]
Yes, I am working on the Home Page. I am currently focused on improving responsiveness as part of my ongoing work.
