### ISSUE TITLE
[UI] consistent navigation bar on all pages 

### ISSUE THREAD

**Issue by Kanha-23** [VigneshDevHub/CampX#113]
**Description**
The home page got very decent navigation bar , as other pages' navigation bar is not that eye catching , i would like to made the consistent navigation bar in all pages .
 
**Current Behavior**
Not having consistent navigation bar in all pages

**Proposed Behavior**
All pages should have similar navbar as the main page.

**Screenshots**
![image](https://github.com/user-attachments/assets/4ff8222f-3376-4af4-88b3-b516944a50a6)
![image](https://github.com/user-attachments/assets/7d1698ba-745f-44db-a6e0-0d43ff8b984d)

**Additional Context**
---

**Impact**
It will look professional

**Related Issues**
---

**Comment by Vignesh025** [comment]
While a consistent navigation bar across all pages is a good idea, using the same navbar as the home page may not look good when scrolling. That’s why we have different navbars for each page."
