### ISSUE TITLE
[UI] Show All Campground using grid view

### ISSUE THREAD

**Issue by MitulSonagara** [VigneshDevHub/CampX#115]
**Description**
I will make all campground cards show using grid view in which it will show as 3 cards in one row in desktop view, 2 cards per row in tablet view and 1 card per row in mobile view.

**Current Behavior**
Currently it is showing one long card per row with not having much content. So it is not looking good coz user need to scroll too much to find campground.

**Proposed Behavior**
Making 3 cards per row and also making it responsive for mobile also.

**Screenshots**
If applicable, add screenshots or mockups to help explain the proposed change.

**Additional Context**
Add any other context, such as references to design guidelines, user feedback, or examples from other applications.

**Impact**
Better user experience

**Related Issues**
Link to any related issues, discussions, or feature requests that are relevant to this UI change.

**Comment by Vignesh025** [comment]
Hey @MitulSonagara , you can proceed. I'm assigning this to you!
