### ISSUE TITLE
[DOC] THERE IS NO CONTACT FORM

### ISSUE THREAD

**Issue by dnyanesh99borse** [VigneshDevHub/CampX#116]
## Description
THERE IS NOT ANY CONTACT FORM ON THE WEBSITE TO GET IN TOUCH WITH THE USERS AND THE DEVELOPERS OF THE APPLICATION TO GET THE FEEDBACK AND ANY CONNECTION TO THE USER.

**Affected Pages**:
- [ ] Other (please specify)
index.html and get add new file as: contact.html

## Type of Documentation Change

- [ ] Update existing documentation

## Additional Context
![image](https://github.com/user-attachments/assets/0855a465-7ff1-43dc-a2fd-92ada7f2f5b3)

## Suggested Improvements

BY PROVIDING THE CONTACT LINK ON THE NAVBAR OF THE HEADER OF THE LANDING PAGE WE CANREDIRECT THE USER TO THE CONTACT FORM AND FROM THERE AFTER FILLING THE FORM THE USER CAN EASILY CONNECT WITH ..

---

**Comment by dnyanesh99borse** [comment]
AS A EXPERIENCED FRONTEND DEVELOPER I AM REQUESTING YOU TO PLEASE ASSING THIS TASK TO ME I CAN RESOLVE THIS ISSUE VERY EFFECTIVELY.

**Comment by Vignesh025** [comment]
Hey @dnyanesh99borse , someone is already working on it. Feel free to explore the project and create new issues!

**Comment by dnyanesh99borse** [comment]
OK
