### ISSUE TITLE
[UI] Fixing the Registration, Login Forms and new campground form

### ISSUE THREAD

**Issue by satyamohlan** [VigneshDevHub/CampX#117]
**Description**
I intend to make the login and registration forms more visually appealing.

**Current Behavior**
Currently, the design of these pages can use a little work.  There is not enough padding. The container Element's too big. The inputs are unnecessarily stretched. I intend to change this into a visually appealing page which is pleasing to look at, uses whitespace and is hierarchical
![image](https://github.com/user-attachments/assets/48945145-4495-40d9-9176-3a9a85c12ed5)

The Image in the form in my opinion, is a bit unnecessary to be honest, given that we already do have a background image of the same nature. Again, We can add a bit more padding and give the inputs outlines, placeholders and the container a black box shadow.
![image](https://github.com/user-attachments/assets/62ebce18-5852-4f52-8cde-d653ee015edd)

**Proposed Behavior**

I intend to make things a little more visually attractive. I was thinking that maybe we could use something like bootswatch.com? It's a library built on top of bootstrap along with a little bit more of character. However, This is just an idea. I can make this better with just vanilla css too.

**Comment by Vignesh025** [comment]
Hey @satyamohlan , someone is already working on the login and register page. I'll check whether they are still working on it and let you know. but feel free to proceed with improving the New Campground and Edit Campground UI.

**Comment by satyamohlan** [comment]
Did you get any update from that person?

**Comment by Vignesh025** [comment]
No, You can proceed!

**Comment by Vignesh025** [comment]
Hey @satyamohlan, what are the pages you're currently working on?

**Comment by Vignesh025** [comment]
Hey @satyamohlan, if I don't hear back from you soon, I may need to assign this issue to someone else. Please let me know if you're still working on it.

**Comment by satyamohlan** [comment]
Hi @Vignesh025  I am really sorry for not keeping you up-to-date. I had been really sick for the past 5 days. So I was not able to do the work. I will send it to you asap now, I promise
