### ISSUE TITLE
[FEATURE] Migrate Frontend to React in Typescript

### ISSUE THREAD

**Issue by khushal1512** [VigneshDevHub/CampX#12]
**Is your feature request related to a problem? Please describe.**
Currently the front-end is written in html, CSS and JavaScript. Migrating the front-end to React in Typescript would be easier to maintain

**Comment by Vignesh025** [comment]
Hi @khushal1512 ,

Thank you for your suggestion regarding migrating the front-end to React in TypeScript. While I appreciate the idea, at the moment, I prefer to keep the project in plain JavaScript.

That being said, migrating to React is something I’m open to, and I encourage you to proceed by transitioning one page at a time. Someone is currently working on the homepage, so you can start with other pages. Please regularly sync the forks to stay updated with new commits.

Thank you again for your contribution, and I look forward to seeing the progress.
