### ISSUE TITLE
[FEATURE]:Add Separate User Page for Hosting and Camp Details

### ISSUE THREAD

**Issue by venurockss** [VigneshDevHub/CampX#121]
Currently, users do not have a dedicated page to showcase their hosted camps or personal information. To enhance user engagement and transparency, we propose adding a separate User Profile Page where users can view and manage details about their hosted camps

**Comment by Vignesh025** [comment]
As I mentioned earlier, we want to keep the project minimal. Adding features like a User Profile Page for managing hosted camps or personal information would make the project overwhelming, so we won't be adding this feature for now.
