### ISSUE TITLE
[FEATURE] Improvement of flash message.

### ISSUE THREAD

**Issue by Suvadip-sana** [VigneshDevHub/CampX#124]
**Problem**
For now the flash message is displaying using bootstrap simple alert message. Particularly for this there is an ISSUE, that is it's not automatically disappeared, need to manually close it or simply refresh the page for closing this, his is very annoying and directly effect to the UX. 
And also the flash message displaying very largely at the top of the screen with big size. That effect the UI of the Web site.
The Issue is here --->

https://github.com/user-attachments/assets/3cb4146e-16ca-4188-b293-104e2f3aa92d

**Describe the solution you'd like**
I want to replace this flash message with *Bootstrap Toasts*. For this the advantage is, it disappeared automatically after 5 second, You can also close it by clicking the close button on it, which is impact the User Experience directly because it's not directly placed on the website content, Just appeared on the screen corner and disappeared automatically.
Like this --> 

https://github.com/user-attachments/assets/317f6ac0-cf14-436c-82de-b71b35997094

 
Could you please assign me this ISSUE. I want to work on this project.

**Additional context**
I am hacktober participant, Please add this tag also if you assign this to me..

**Comment by Vignesh025** [comment]
Hey, someone is already working on the flash messages. Feel free to explore the project and create new issues!
