### ISSUE TITLE
[FEATURE]Add details about the place when hovering on the map pointer.

### ISSUE THREAD

**Issue by Suvadip-sana** [VigneshDevHub/CampX#126]
**ISSUE**
After Adding new list, the pointer was pointed that particular location using mapbox map pointer. But there must be a feature like when hovering on that pointer it show which place it is.
Just like this --->

https://github.com/user-attachments/assets/40dfa89c-5cc3-4145-b716-b0cb0f010e86

**Solution**
I want to add this feature. Because I work with mapbox map integration on webpage, and I am expert of the mapbox map integration with the help of Mapbox documentation, It help to enhance the user experience.

Please assign me this ISSUE. I want to developed this feature in mapbox map integration.

**Additional context**
Please add gssoc-exted, hacktoberfest, point label if you assign to me.

**Comment by Vignesh025** [comment]
Hey @Suvadip-sana , you can proceed. I'm assigning this to you.

**Comment by Suvadip-sana** [comment]
@Vignesh025 Thank you.

**Comment by Suvadip-sana** [comment]
@Vignesh025 

https://github.com/user-attachments/assets/63d84a04-a08a-477a-a36d-0195446e4b79

It's ready should i make a PR?

**Comment by Suvadip-sana** [comment]
@Vignesh025  Please tell me.

**Comment by Vignesh025** [comment]
> It's ready should i make a PR?

Hey @Suvadip-sana, we don’t need this feature in the view page. Please implement this feature only in the cluster map. Thanks!

**Comment by Suvadip-sana** [comment]
@Vignesh025 

Ok but could you please merge this? Because it's also an attractive for user?
I made an another seperate issue for this. It would be also good for me..

Tell me what you say for this?

**Comment by Vignesh025** [comment]
Hey @Suvadip-sana , since we're already inside the view page of the campground, I don't think it's necessary to hover to get the title of the ground on the map within the view page.

**Comment by Suvadip-sana** [comment]
@Vignesh025 So what should I do for now?

**Comment by Vignesh025** [comment]
Only have this feature on the cluster map on the campgrounds page.

**Comment by Suvadip-sana** [comment]
Ok. I try my best.

**Comment by Suvadip-sana** [comment]
@Vignesh025 

Here in cluster map, in which hover effect need to be  apply? and exactly what to display? Please tell me. 


**In my opinion.**

1) First when hovering on the cluster point(numbered marker) then it show the number of campground in this cluster zone. It's needed because normal user did not understand what this number on pointer wants to say. 

2) Secondly when hovering on the individual marker point then when hover on the marker it show this particuler location information. (what I do for show camping site initially)


Tell me what's your opinion, particularly for this things.

**Comment by Vignesh025** [comment]
> 1. First when hovering on the cluster point(numbered marker) then it show the number of campground in this cluster zone. It's needed because normal user did not understand what this number on pointer wants to say.
> 2. Secondly when hovering on the individual marker point then when hover on the marker it show this particuler location information. (what I do for show camping site initially)

@Suvadip-sana , I want exactly the same. You can proceed.

**Comment by Suvadip-sana** [comment]
@Vignesh025 


https://github.com/user-attachments/assets/d3719b4a-08c9-4337-a564-9026af3a9841



Please give me label-2 or label-3. Because it's take way more time as i thought because of research. Reading documentation.
Although i raise the issue for apply the hover effect on show campground pages map. But you tell me to do this insted of this.
It's absolute new experience for me with cluster map. And also there was many bugs with your code to apply hover effect initially.

So please consider this. I create a PR for this. ok?
Thank You.

**Comment by Vignesh025** [comment]
You can proceed!

**Comment by Suvadip-sana** [comment]
@Vignesh025 I create a PR. Check it out
