### ISSUE TITLE
[UI]Displaying Reviews are not visually appealing for users & need to add validation message

### ISSUE THREAD

**Issue by Suvadip-sana** [VigneshDevHub/CampX#127]
**Description**
When you display the reviews for the camp site, The stars are too much big, which is not good looking at all. It should be smaller, which i want to create manually just like this --> 

![image](https://github.com/user-attachments/assets/642d7542-a721-45e5-a026-41ba9bce51d7)
Which is looks like more appealing.

Also want to add a review form validation message in case user try to submit the form with out writing anything in review section field. 
Just like this -->
![image](https://github.com/user-attachments/assets/bb657512-7e26-43fa-9ae4-febe91670047)

I want to work on it. Please assign me that ISSUE. 

**Additional context**
Please add gssoc-exted, hacktoberfest, point label if you assign to me.

**Comment by Vignesh025** [comment]
Sure @Suvadip-sana , you can work on making the reviews visually appealing, but please don't work on the validation.

**Comment by Suvadip-sana** [comment]
Ok got it. @Vignesh025

**Comment by Suvadip-sana** [comment]
![Uploading image.png…]()
This was also ready. Tell me is this ok?

Then I create a PR.
@Vignesh025

**Comment by Vignesh025** [comment]
You can proceed with the PR.
