### ISSUE TITLE
[FEATURE] there should be a feature if any person created a new campground the email is sent to them for successfully created a campground.

### ISSUE THREAD

**Issue by anuj-pal27** [VigneshDevHub/CampX#13]

**Comment by anuj-pal27** [comment]
i want to work on this can you assign it to me .

**Comment by Vignesh025** [comment]
@anuj-pal27 sure, go head!

**Comment by Vignesh025** [comment]
Hey @anuj-pal27 , are you still working on this issue? If not, please let me know so I can assign it to someone else. Thanks!

**Comment by anuj-pal27** [comment]
@Vignesh025  i need some time , can you please label it hacktoberfest

**Comment by Vignesh025** [comment]
Thanks for the update! Also, please try to give an update now and then so we're all on the same page

**Comment by Vignesh025** [comment]
Hey @anuj-pal27 , are you still working on this issue? If not, please let me know so I can assign it to someone else. Thanks!
