### ISSUE TITLE
[FEATURE] transition  and loading animation on switching tabs

### ISSUE THREAD

**Issue by harsh7274v** [VigneshDevHub/CampX#130]
on switching to home , campgrounds or new campgrounds  tabs it needs enhancement . it directly displaying the webpage .
it need animation and some transitions . it looks and make user a friendly environment during switching or  moving the tab.

**Comment by Vignesh025** [comment]
Hey @harsh7274v ,I don't think adding animations or transitions will fit well with our project, so we won't be implementing this. Feel free to explore the project and suggest any other ideas!
