### ISSUE TITLE
[FEATURE] Implement automated Task

### ISSUE THREAD

**Issue by hamzathul** [VigneshDevHub/CampX#131]
**Is your feature request related to a problem? Please describe.**

Our open-source website hosted on Render experiences downtime every 15 minutes, taking approximately 1 minute to become accessible again. This consistent downtime affects user experience and the accessibility of our resources.

**Describe the solution you'd like**

To mitigate this issue and ensure that our website remains live at all times, I propose implementing a automated job that will periodically ping our website to keep it active, it send https request in every 14 minutes. This would prevent it from going to sleep or entering an idle state, thereby reducing the downtime.

Please assign me, i can fix this.
i have done this in my personal projects deployed on render.

#hacktoberfest #gssoc-ext

**Comment by Vignesh025** [comment]
Hey @hamzathul , You can proceed. I'm assigning this to you.
