### ISSUE TITLE
[BUG] : Margin Issue in the Login And Register page and add spacing between in landing page of navbar

### ISSUE THREAD

**Issue by rupeshv2121** [VigneshDevHub/CampX#134]
Margin Issue in the Login And Register page and add spacing between in landing page of navbar

![Footer](https://github.com/user-attachments/assets/d7891784-58ea-4f40-a975-878bfe97e26d)
![Register](https://github.com/user-attachments/assets/4426b5e9-576b-4eb7-826b-646c69dbe9a8)
![Spacing](https://github.com/user-attachments/assets/e6750b42-c5d5-4d0c-ae37-185a7928b873)

pls assign me under label gssoc-ext, hacktoberfest-accepted

**Comment by Vignesh025** [comment]
Hey @rupeshv2121 , someone is already working on that issue. Feel free to explore the project and create new issues!
