### ISSUE TITLE
[FEATURE] IMPLEMENT SIGN UP/ SIGN IN USING GOOGLE.

### ISSUE THREAD

**Issue by youraj-08** [VigneshDevHub/CampX#145]
**Problem**
The project currently lacks a "Sign up with Google" feature. This limits the ease of user onboarding, as many users prefer signing up with their Google accounts for faster and more secure access, rather than manually creating a new account.

**Solution**
I want to work on adding a "Sign up with Google" feature to the application. This would integrate Google's OAuth 2.0 authentication, allowing users to register or log in with their Google accounts, streamlining the registration process and improving user experience.

**Comment by Vignesh025** [comment]
We don't want to take on any authentication features at this moment.
