### ISSUE TITLE
[FEATURE] Adding the contributors page to mention all the awersome people who have contributed to the website.

### ISSUE THREAD

**Issue by tarunkumar2005** [VigneshDevHub/CampX#146]
Adding the contributors page to mention all the awersome people who have contributed to the website.

@Vignesh025 Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this isssue.

**Comment by Vignesh025** [comment]
We already have our contributors profile in the project's Readme.

**Comment by tarunkumar2005** [comment]
@Vignesh025 But in website it will be more better any every person might not visit your repo but on your website will there we can showcase but its your choise if you don't want then its fine.
