### ISSUE TITLE
[UI] improve UI of authentication page

### ISSUE THREAD

**Issue by abhijeetmishra2104** [VigneshDevHub/CampX#154]
**Description**
adding functionality to navigate from register page to login page if user already have an account and vice versa. Adding functionality to show the password. And a better looking UI.

**Current Behavior**
currently, user have to use navigation bar to switch between login and register page. And UI is not that good. User can't see their password.

**Proposed Behavior**
adding an option "Already have an account? Login" while registering and "Don't have an account? Register" while login at the bottom of the form. User will be able to see their password.

**Screenshots**
<img width="623" alt="Screenshot 2024-10-12 at 1 11 51 PM" src="https://github.com/user-attachments/assets/76978e23-0693-44c4-be3f-dca44e7890e5">

**Additional Context**
in the new design, the image will be shown on the left hand side while the form will be on the right hand side.

**Impact**
it will improve accessibility and visual apeal.

**Related Issues**
ref #3

**Comment by Vignesh025** [comment]
Hey @abhijeetmishra2104 , This feature already exists.
