### ISSUE TITLE
[BUG] Map pointer not updating when location was changed after adding new site.

### ISSUE THREAD

**Issue by Suvadip-sana** [VigneshDevHub/CampX#155]
**Describe the bug**
After adding a new camping site. When I going to change the location the location changes reflect on the database but map pointer not updating in the map. It's a big flaw of the server. Need to fix this, because location changes suppose to be reflect on the map too. But it's not happening.

Need some work on backend, need to check & add logic on backend.
 
**To Reproduce**
1. Go to 'Campgrounds'
2. Click on 'View Campground'
3. Click on 'Edit'
4. Change the location.
5. Then see the map pointer not updating. Still on the previous marker.

**Expected behavior**
It supposed to be change the marker on map when I change the location It self.

For better understanding see the attached video.

**Screenshots**

https://github.com/user-attachments/assets/abc1356a-58ef-4f76-9f39-ce396354eb1b

**Desktop (please complete the following information):**
 - OS: [W11]
 - Browser [All]

**Additional context**
Please assign me this task, I want to fix this. 
It need a pretty much backend work to resolve this ISSUE.  @Vignesh025  

**NOTE** please add all the necesssary label as per guidline, including hacktoberfest-accepted.

**Comment by Vignesh025** [comment]
@Suvadip-sana , you can proceed. I'm assigning this to you.
