### ISSUE TITLE
[FEATURE] The UI/UX of the login/Signup Page is not that good i want to improve that

### ISSUE THREAD

**Issue by tarunkumar2005** [VigneshDevHub/CampX#157]
[FEATURE] The UI/UX of the login/Signup Page is not that good i want to improve that

@Vignesh025 Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by Vignesh025** [comment]
Hey @tarunkumar2005 , you can proceed. I'm assigning this to you,
