### ISSUE TITLE
[FEATURE] Enhanced Errors UI with a custom Toast

### ISSUE THREAD

**Issue by tarunkumar2005** [VigneshDevHub/CampX#158]
Enhanced Errors UI with a custom Toast.

![image](https://github.com/user-attachments/assets/01fc07f7-6584-4fae-b2b4-080927437f8a)

@Vignesh025  Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by Vignesh025** [comment]
Hey @tarunkumar2005, we don't require this feature at the moment.
