### ISSUE TITLE
[FEATURE] Improving the search functionality continous searching as the user enters the text in search box.

### ISSUE THREAD

**Issue by tarunkumar2005** [VigneshDevHub/CampX#159]
Improving the search functionality continous searching as the user enters the text in search box.

@Vignesh025 Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by Vignesh025** [comment]
@tarunkumar2005 , you can proceed!

**Comment by tarunkumar2005** [comment]
@Vignesh025 I don't have mapbox token and account how will i test it and it is not starting the server without mapbox and when creating it is asking for payment what can i do.

**Comment by Vignesh025** [comment]
> @Vignesh025 I don't have mapbox token and account how will i test it and it is not starting the server without mapbox and when creating it is asking for payment what can i do.

Hey @tarunkumar2005 , if you signup using your college mail id, it wont ask for any bank details
