### ISSUE TITLE
[BUG]Missing Start Script ,  

### ISSUE THREAD

**Issue by adilkadivala** [VigneshDevHub/CampX#16]
**Description**
Every project have a start script,  but unfortunally we haven't it,  

**To Reproduce**
1. Go to 'package.json'
2. in Scripts 'write start and give it access of root file of project'

**Expected behavior**
in log should be print 'Serving on port 3000'

**Screenshots  of current facing error **
![project setup](https://github.com/user-attachments/assets/03066f9b-615e-476c-b5ce-f18c0264f90c)

**Comment by Aditya-NV-06** [comment]
This can be solved by running npm install in the project after cloning the repo.After that run the 
npm start command in the terminal.This should be in the root folder of the project
