### ISSUE TITLE
[FEATURE] Adding filter button to filter out some campsites and get more relevent ones.

### ISSUE THREAD

**Issue by tarunkumar2005** [VigneshDevHub/CampX#160]
Adding filter button to filter out some campsites and get more relevent ones.

@Vignesh025 Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by Vignesh025** [comment]
Hey @tarunkumar2005, on what basis are you planning to filter the campgrounds?

**Comment by tarunkumar2005** [comment]
We can filter based on cost like this much min to this much max and like location like it is mountain, park, lake or so, type of activity we can do there like hicking, fishing, boating, swimming and so other options can be there

**Comment by Vignesh025** [comment]
Hey @tarunkumar2005, we already have filters for cost and reviews, and we don't require filters for other things at the moment.
