### ISSUE TITLE
Login and Register Pages Overlap in Footer Section and Missing Box Shadow

### ISSUE THREAD

**Issue by ansiace** [VigneshDevHub/CampX#162]
Bug 1: Login and Register Pages Overlap in Footer Section
The layout of the Login and Register sections currently touches the footer, creating an awkward and cramped design. There should be adequate spacing between the sections and the footer to improve readability and design aesthetics.

Expected Behavior:
There should be sufficient spacing between the Login/Register forms and the footer.

Bug 2: Missing Box Shadow on Login Page
In the Login page, the form lacks the subtle box shadow present on the Register page, which creates a design inconsistency between the two forms.

Expected Behavior:

The Login form should have a similar box shadow effect as the Register form for consistency in design.

![Screenshot 2024-10-13 025419(1)(1)](https://github.com/user-attachments/assets/2a57c71e-8669-4d28-b894-76e23493906a)
![Screenshot 2024-10-13 025514(1)(1)](https://github.com/user-attachments/assets/229e132e-47c5-43ad-8003-45ea85da7eb7)

**Comment by Vignesh025** [comment]
Hey @ansiace , someone else is already working on this issue. Feel free to explore and create new issues!

**Comment by ansiace** [comment]
Ok Fine

**Comment by ansiace** [comment]
I noticed that till now the issue the issue is not resolved. I would love the opportunity to contribute to the project by working on this issue. Can you please assign if i'll raise an issue?

**Comment by Vignesh025** [comment]
It is resolved. we were working on the deployment and now its done.
