### ISSUE TITLE
Adding information about campgrounds

### ISSUE THREAD

**Issue by Gauravtb2253** [VigneshDevHub/CampX#166]
Hello
I would like to add more information about every campground when the users view it

**Comment by Vignesh025** [comment]
can you please specify what kind of additional information you going to add?

**Comment by Gauravtb2253** [comment]
> can you please specify what kind of additional information you going to add?

We can add description, amenities near the camp, activities to perform, weather information and such things

**Comment by Vignesh025** [comment]
Hey @Gauravtb2253 ,We want to keep the description of the campground simple and not overloaded with too much information. Adding too many details like amenities, activities, and weather can clutter the page. Let's keep it basic for a clean and user-friendly experience.
