### ISSUE TITLE
[UI] New Web Icon

### ISSUE THREAD

**Issue by Vignesh025** [VigneshDevHub/CampX#17]
#### Description
We need a more attractive web icon for the website.

#### Current Behavior
The current Web icon is minimalist.

**Comment by Sauhard74** [comment]
i can help you create a minimal yet intrusive icon

**Comment by Vignesh025** [comment]
Thankyou @Sauhard74 , I'm assigning this to you. Proceed!

**Comment by Vignesh025** [comment]
Hey @Sauhard74 , are you still working on this issue? If not, please let me know so I can assign it to someone else. Thanks!

**Comment by Sauhard74** [comment]
Hey I have made the webicon can you open it again as I was planning to post it 
...sorry I was busy in some personal work that's why I missed it 

Can you open it again ?

**Comment by Vignesh025** [comment]
Please try to update now and then.

**Comment by Sauhard74** [comment]
![ezgif-3-b79751d3f9](https://github.com/user-attachments/assets/a293e185-f27b-41eb-ab82-44c733850f95)

this is the jpg image of the webicon i designed 
i can share the webp , SVG image , can you help me make a pr of this? i don't know how to make pr of no code works
