### ISSUE TITLE
[UI] alignment correction 

### ISSUE THREAD

**Issue by Nbisht1208** [VigneshDevHub/CampX#178]
**Description**
Responsive issue 

**Current Behavior**
Search bar is not responsive 

**Proposed Behavior**
I will fix the size and align the search bar portion 

**Screenshots**
![Screenshot_2024-10-14-08-53-42-613_com android chrome](https://github.com/user-attachments/assets/efcd0cbf-79cc-40a3-9e0a-fd3487f59342)

**Additional Context**
Add any other context, such as references to design guidelines, user feedback, or examples from other applications.

**Impact**
Explain the potential impact of this change. Will it improve usability, accessibility, performance, or visual appeal?

**Related Issues**
Link to any related issues, discussions, or feature requests that are relevant to this UI change.

**Comment by Nbisht1208** [comment]
Can you provide the mapbox_token?

**Comment by Vignesh025** [comment]
If you're not working on the map, you can comment out the part and work.

**Comment by Nbisht1208** [comment]
@Vignesh025 i am working on the alignment of my search bar not map

**Comment by Nbisht1208** [comment]
Can you provide the mapbox_token??
