### ISSUE TITLE
[FEATURE] Improvement of navigation bar.

### ISSUE THREAD

**Issue by HarshtheGeek** [VigneshDevHub/CampX#179]
**Is your feature request related to a problem? Please describe.**
The current website lacks a navigation bar, making it difficult for users to navigate through different sections. This issue hampers user experience, as visitors are unable to easily access various parts of the site. A well-designed navigation bar is crucial for enhancing usability and ensuring that users can effortlessly find the information they need.

**Describe the solution you'd like**
Add a logo to the left side of the navigation bar to establish brand identity, Implement hover effects such as color changes, underlines, or background highlights to indicate interactive elements.

**Describe alternatives you've considered**
Addition of scroll progress bar

**Additional context**
I would like to add something like this 
![Screenshot (577)](https://github.com/user-attachments/assets/bd6a0d43-7d09-41ab-a07b-2947b486d1d8)

kindly assign me the task.

**Comment by Vignesh025** [comment]
Hey @HarshtheGeek , we already have a navbar and we don't require a scroll progress bar anytime soon.
