### ISSUE TITLE
[FEATURE] Provide an option to sort campgrounds based on current location of the user

### ISSUE THREAD

**Issue by memyselfandglitch** [VigneshDevHub/CampX#18]
**Issue**
When the user registers and views all the campgrounds he will have a button in the /campgrounds route which has all the campgrounds to sort all them from his current location. This will be handy as he/she won't have to look through the map to find the closest campgrounds. 

**Solution**
A button to show the nearest campgrounds based on users location

**Comment by Vignesh025** [comment]
Hi @memyselfandglitch ,

Thank you for the great idea of adding a feature to sort campgrounds based on the user's current location. I agree that it would enhance user convenience, and you can proceed with implementing this feature.

I’m assigning this issue to you. Please ensure that you sync the repo regularly to stay up to date with any new commits and avoid conflicts.

Looking forward to seeing the progress!
