### ISSUE TITLE
[UI] Enhancing the Landing Page

### ISSUE THREAD

**Issue by itsadi-24** [VigneshDevHub/CampX#184]
I would like to redesign and refactor the landing page,while improving the layout and fonts.
I would also like to improve the navbar.

![Screenshot 2024-10-15 014108](https://github.com/user-attachments/assets/f63190c6-f26b-42c1-8fdb-b0f4d11d40ab)
As you can see that from the current version lot of improvements can be made.
I would like to work on it.

**Comment by Vignesh025** [comment]
Hey @itsadi-24 , You can proceed!

**Comment by itsadi-24** [comment]
![Screenshot 2024-10-17 094438](https://github.com/user-attachments/assets/5050d4ab-76aa-4298-9fd5-e2f0a0107615)
![Screenshot 2024-10-17 093401](https://github.com/user-attachments/assets/e9d7c128-a9fc-4cfe-b9e2-e28dd05e0fb6)
Hi @Vignesh025 which one do you prefer,there is little modification left for both,i will proceed as per your choice.

**Comment by itsadi-24** [comment]
in 1st one the background image will also change with time

**Comment by Vignesh025** [comment]
The first one is fine, but remove the privacy and terms from the footer.

**Comment by itsadi-24** [comment]
ok working on it

**Comment by itsadi-24** [comment]
Hi @Vignesh025 i have made the PR #228
