### ISSUE TITLE
[UI] Navbar

### ISSUE THREAD

**Issue by Bhum-ika** [VigneshDevHub/CampX#185]
**Description**
The whole navbar is degrading the website

**Current Behavior**
It sis very basic and has 0 to no styling

**Proposed Behavior**
It should attract users and improve user experience.

**Screenshots**
![image](https://github.com/user-attachments/assets/90743df2-7ddc-43e1-b92f-fb804e1efbd5)

**Additional Context**
**Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.**

**Impact**
Imporve visual appeal

**Comment by Bhum-ika** [comment]
Hey @Vignesh025 IS there any dummy mapbox token I can use

**Comment by Vignesh025** [comment]
Hey @Bhum-ika , as you're not working with the map, you can comment out the map part and focus on the navbar. This way, you won't need any mapbox token.

**Comment by Bhum-ika** [comment]
Okay :)
