### ISSUE TITLE
[BUG]: Redirection Issue : Clicking on CampX Logo Reloads Same Page

### ISSUE THREAD

**Issue by faiz66388** [VigneshDevHub/CampX#187]
Description:
When clicking on the CampX logo in the navigation bar, it reloads the current page instead of redirecting to the home page as expected.

Steps to Reproduce:
Go to any page within the application, such as the login page.
Click on the "CampX" logo in the top-left corner of the navigation bar.
Expected Behavior:
Clicking on the "CampX" logo should redirect the user to the home page.

Actual Behavior:
Clicking on the "CampX" logo reloads the current page instead of redirecting to the home page.

Screenshots/Logs:
![image](https://github.com/user-attachments/assets/0f04c894-fd6c-42ea-933b-5ee71a24c3c9)

**Comment by Vignesh025** [comment]
Hey @faiz66388 , you can proceed!

**Comment by faiz66388** [comment]
Could you please assign labels gssoc-ext, hacktoberfest-accepted and level?

**Comment by raj-adi00** [comment]
Is this issue open?? i can work on this

**Comment by Vignesh025** [comment]
Hey @raj-adi00 , You can proceed!

**Comment by raj-adi00** [comment]
@Vignesh025 Please confirm whether this issue still exist. I checked it is implemented on campgrounds page but not on home page

**Comment by raj-adi00** [comment]
Do you want me to implement it on home page or you can close the issue

**Comment by Vignesh025** [comment]
@raj-adi00 , yes the issue is solved.
