### ISSUE TITLE
[FEATURE]Want to improve the website

### ISSUE THREAD

**Issue by Dipanita45** [VigneshDevHub/CampX#188]
**Is your feature request related to a problem? Please describe.**
Update or add  css properties

**Describe the solution you'd like
Added features like opacity, transition, colour ,.. etc

Please assign me the issue @Vignesh025 
Thank you!!

**Comment by Vignesh025** [comment]
Hey @Dipanita45 ,Please elaborate on what page are you going to work and on what feature?

**Comment by Vignesh025** [comment]
Someone is already working on the whole homepage!

**Comment by Dipanita45** [comment]
Okay

**Comment by Dipanita45** [comment]
Please assign it to me I will modify the whole pages

**Comment by Vignesh025** [comment]
Please tell me on which exact feature you want to work. Only then I can decide.

**Comment by Dipanita45** [comment]
Want to add more features like transition, colour contrast and more in the
pages
