### ISSUE TITLE
MAPBOX_TOKEN missing in .env

### ISSUE THREAD

**Issue by ARRY7686** [VigneshDevHub/CampX#19]
## Description

In the Installation Guide, the documentation fails to mention the need to create a MAPBOX_TOKEN in the .env file. Without this token, the server will not start, resulting in an error:
```
Error: Cannot create a client without an access token
    at NodeClient.MapiClient (/path/to/node_modules/@mapbox/mapbox-sdk/lib/classes/mapi-client.js:25:11)
```

**Affected Pages**:
- [ ] README.md
- [x] Installation Guide
- [ ] Configuration Guide
- [ ] Other (please specify)

## Type of Documentation Change

- [x] Update existing documentation
- [ ] Add new documentation
- [ ] Remove outdated or redundant documentation
- [ ] Other (please specify)

## Additional Context
When following the installation steps, users encounter an error due to the missing MAPBOX_TOKEN environment variable. The documentation should explicitly instruct users to include the MAPBOX_TOKEN in the .env file to avoid this issue.

## Suggested Improvements

Update the Installation Guide to include instructions for setting up the .env file, specifically adding:

`MAPBOX_TOKEN=<your_mapbox_token_here>`

This change will ensure that users are aware of the required Mapbox token and avoid runtime errors related to missing environment variables.

---

**Comment by Vignesh025** [comment]
Sure @ARRY7686 , I'm assigning this to you. Proceed!

**Comment by ARRY7686** [comment]
hi @Vignesh025 just an update on the progress I have finished the work and the PR will be raised on 1st october as soon as the hacktober fest commences

**Comment by Vignesh025** [comment]
Hi @ARRY7686 ,

Thank you for the update! That sounds great—raising the PR on October 1st works perfectly. Looking forward to seeing it once Hacktoberfest starts!

**Comment by ARRY7686** [comment]
hi @Vignesh025 i have raised the PR adressing the issue kindly merge it
