### ISSUE TITLE
[UI]Add hover effects 

### ISSUE THREAD

**Issue by MaahiVaghela** [VigneshDevHub/CampX#191]
Adding hover effects to cards and buttons. Please assign this task to me

**Comment by Vignesh025** [comment]
Hey @MaahiVaghela , can you tell me on which page you are going to work?

**Comment by MaahiVaghela** [comment]
![image](https://github.com/user-attachments/assets/b524ec8b-5a2c-432f-bc85-81bf00562055)

**Comment by Vignesh025** [comment]
You can proceed!

**Comment by MaahiVaghela** [comment]
can you add gssoc-ext label too ?
