### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dhruvishah122** [VigneshDevHub/CampX#195]
Search bar and show nearest to me buttons are not responsive in mobile. UI bug is there. I have attached the screenshot pls check.

**Additional context**
![Screenshot_20241016_124608_Samsung Internet](https://github.com/user-attachments/assets/39e610fb-100a-4f2f-b57e-495a61522d75)

**Comment by Goutamchoudhary907** [comment]
Hey @Vignesh025  i want to work on this can you assign me this

**Comment by Vignesh025** [comment]
Hey @dhruvishah122 , you can proceed!

**Comment by raj-adi00** [comment]
Is this issue open. I can work on this

**Comment by Vignesh025** [comment]
Hey @raj-adi00 , this is issue is fixed now.
