### ISSUE TITLE
[UI] UI change for Register Page

### ISSUE THREAD

**Issue by Vignesh025** [VigneshDevHub/CampX#2]
**Description**
Improve the UI of Register page to be more attractive.

**Current Behavior**
The current UI is minimalist.

*If you're going to work on this issue, create a new issue explaining your changes and mention this issue.*

**Comment by BinaryBhakti** [comment]
I want to work on this issue. Please assign this issue to me.

**Comment by Vignesh025** [comment]
Hey @BinaryBhakti , Create a new issue stating all the changes you want to make and mention this issue like (issue #2). I'll review it and assign it to you.

**Comment by BinaryBhakti** [comment]
I have created a issue with the name #22 , so do review it.

**Comment by Vignesh025** [comment]
@BinaryBhakti , I reviewed your issue. Please check it out. Thank you!

**Comment by itsadi-24** [comment]
@Vignesh025 you can assign me this issue

**Comment by itsadi-24** [comment]
Hi @Vignesh025 can you add hactoberfest-accepted and gssoc-ext to it.Thanks!
