### ISSUE TITLE
Contributing & Forking Issue

### ISSUE THREAD

**Issue by stacknomad** [VigneshDevHub/CampX#20]
So... let's say that I wanted to contribute this project and began forking it. Even after following the [contributing guidelines](https://github.com/VigneshDevHub/CampX/blob/main/CONTRIBUTING.md), I'm left with an non-working and broken local project. It would be impossible to make the changes you want to make without having to make more unrelated changes that should have already been there.

Things like, the `.env` file and a guide to getting that to work with the code, so that any and all secrets required by the project is provided without having to change the main codebase just to get it working for you locally.

Although they are free, you'll have to make accounts in order to get those API keys and secrets needed.

*I made the necessary fixes for these issues and also updated the `CONTRIBUTING.md` file for documentation.*

**Comment by Vignesh025** [comment]
Hi @stacknomad ,

Thank you so much for your valuable feedback and for taking the time to work on the necessary fixes for the project. I appreciate your initiative in resolving the issues related to the ``.env`` file and improving the contributing guidelines.

As a suggestion, it would be great if you could break down your changes into smaller, focused commits. This will make it easier to review and merge the updates one step at a time, ensuring each set of changes is tested thoroughly. For example:

- One commit could address the fixes for ``.env`` and related secrets.
- Another commit can focus on updating the ``CONTRIBUTING.md`` file for documentation.

Once you've made these commits, feel free to open separate pull requests, and I’ll be happy to review them promptly.

Thank you again for your efforts, and I look forward to seeing your contributions!

**Comment by Vignesh025** [comment]
Hey @stacknomad , are you still working on this issue? If not, please let me know so I can assign it to someone else. Thanks!
