### ISSUE TITLE
Vehicle Space Specification

### ISSUE THREAD

**Issue by ykchoudhary110** [VigneshDevHub/CampX#201]
Description: Allow users to specify the number of vehicles and space dimensions (in feet or meters) a campground can accommodate. This information will help campers with RVs or multiple vehicles or add the vechile dimmesion for that on the campside place

Solution:
Add fields for number of vehicles and space dimensions.
Ensure this information is displayed in the campground details.

Label: Enhancement, frontend, backend
Priority: Medium

**Comment by Vignesh025** [comment]
Hey @ykchoudhary110 , thank you for the suggestion, but we don't need this feature at the moment.
