### ISSUE TITLE
Campground Safety Features

### ISSUE THREAD

**Issue by ykchoudhary110** [VigneshDevHub/CampX#202]
Description: Create an option for users to specify safety features such as fire pits, first aid availability, and security services. Users can select multiple options from a list.

Task:
Add a checkbox or dropdown for safety features when adding/editing a campground.
Display these features as icons in the campground listing.

Label: enhancement, UI, backend
Priority: High

**Comment by Vignesh025** [comment]
Thank you for the suggestion, but we don't need this feature at the moment.

**Comment by ykchoudhary110** [comment]
Dear Vignesh 
      As you have reopened it so shall I start working on this feature or not ?

**Comment by Vignesh025** [comment]
Thank you for the suggestion, but we don't need this feature at the moment.
