### ISSUE TITLE
Add Zoom Effect on Hover for 'View Campgrounds' Button

### ISSUE THREAD

**Issue by Shreyhac** [VigneshDevHub/CampX#203]
The "View Campgrounds" button currently has no visual effect when hovered over, which makes the user interaction feel static. Adding a smooth zoom effect on hover will enhance the user experience, making the button more interactive and visually appealing.

Expected Behavior: When a user hovers over the "View Campgrounds" button, the button should smoothly scale up (zoom in) slightly to draw attention and indicate interactivity.

.view-campgrounds-button {
    transition: transform 0.2s ease-in-out;
}

.view-campgrounds-button:hover {
    transform: scale(1.05);
}

Expected Result: When the user hovers over the button, it should zoom in smoothly by 5%, providing a more dynamic feel.
Additional Context: This small enhancement will improve the overall user interface, making buttons more intuitive and engaging. It is especially helpful in drawing attention to call-to-action buttons like "View Campgrounds."

<img width="293" alt="Screenshot 2024-10-17 at 01 59 09" src="https://github.com/user-attachments/assets/1c1174b7-ad67-4703-8382-d6bf5bacf220">

**Comment by TanishaMehta17** [comment]
@Vignesh025 Can you please assign me this issue

**Comment by Shreyhac** [comment]
@Vignesh025 i have already started working on it

**Comment by Vignesh025** [comment]
Hey @Shreyhac , Someone is already working on the UI of the homepage.
