### ISSUE TITLE
[BUG] Image not visible

### ISSUE THREAD

**Issue by Mansi07sharma** [VigneshDevHub/CampX#204]
**Describe the bug**
One image is not visible

**To Reproduce**
1. Go to website
2. Scroll down to last

**Expected behavior**
to be visible
**Screenshots**
![image](https://github.com/user-attachments/assets/864af69f-d236-4013-bed6-1c4e30ad135f)

**Desktop (please complete the following information):**
 - Browser [chrome]

Kindly assign me i will solve it @Vignesh025

**Comment by Vignesh025** [comment]
Hey, can you please tell me how you will make the unuploaded image visible?
