### ISSUE TITLE
[UI]Fix the campx logo, cause of distraction 

### ISSUE THREAD

**Issue by AE-Hertz** [VigneshDevHub/CampX#207]
**Description**
The campx logo is causing a distraction with fast moving.

**Current Behavior**
 Fast moving.

**Proposed Behavior**
Will have a timeout between each campx logo animation, to be a settle and aesthetic.

Assign me this task under gssoc-ext and hacktoberfest

**Comment by Vignesh025** [comment]
Thank you for your effort, but we don't require this fix at the moment.
