### ISSUE TITLE
[FEATURE] Adding Error Handling Middle-Ware

### ISSUE THREAD

**Issue by DevKanmi** [VigneshDevHub/CampX#212]
#### Adding an Error Handling Middleware to properly and gracefully handle most error Messages that might occur.
- A new file would be created called errorHandler
- app.js can use the errorHandler by calling app.use(errorHandler) a function in the errorhandler file.

I would like to work on this if needed.

**Comment by Vignesh025** [comment]
Hey @DevKanmi , You can proceed!

**Comment by DevKanmi** [comment]
Alright, thank you!
