### ISSUE TITLE
Will add Testimonals feedback and Contact us section on website .

### ISSUE THREAD

**Issue by simran0809** [VigneshDevHub/CampX#213]
**Describe the bug**
Testimonials: Reviews or feedback from previous campers or parents.
Contact Us: A way for people to get in touch (phone number, email, etc.). 
i will add feedback sections also try to add styling on camp website .

**Desktop 

**Smartphone (please complete the following information):**

Thankyou

**Comment by Vignesh025** [comment]
Hey, thank you for the suggestion, but we don't need this feature anytime soon. Appreciate your input though!
