### ISSUE TITLE
[DOC]: Enhancement Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [VigneshDevHub/CampX#215]
## Description

The contributing.md looks is not in a structured manner. Also some sections are missing. I can enhance it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute. Please can you assign me this task?

**Affected Pages**:
- [ ] README.md
- [ ] Installation Guide
- [ ] Configuration Guide
- [x] CONTRIBUTING.md
- [ ] Other (please specify)

## Type of Documentation Change

- [x] Update existing documentation
- [ ] Add new documentation
- [ ] Remove outdated or redundant documentation
- [ ] Other (please specify)

## Additional Context

-----------------------

## Suggested Improvements

Wanted to do the following changes :-

1) Enhance the project structure
2) Add project structure section
3) Add additional method of contributing through GitHub desktop section
4) Add good coding practices section
5) Add the help and support section
6) Add the pull request section
7) Add issue report process section

---

**Comment by milansamuel609** [comment]
> Hey @milansamuel609 , You can proceed!

Please can you attach the label of gssoc extend also. I contributing under both. Thank so much for this opportunity to contribute. I will do my best 👍

**Comment by Vignesh025** [comment]
Hey @milansamuel609 , I'm really happy with your contribution. Can you do the same for Readme.md?

**Comment by milansamuel609** [comment]
> Hey @milansamuel609 , I'm really happy with your contribution. Can you do the same for Readme.md?

Thank you so much for the appreciation. Sure I can 👍.
