### ISSUE TITLE
[UI] I want to improve the UI of campgrounds page

### ISSUE THREAD

**Issue by anishka25** [VigneshDevHub/CampX#218]
**Description**
I want to improve the buttons on that page, the color of the search and show nearest to me do not follow the general color scheme as well as their alignment is not in place. I want to also add hover effect on the buttons , all these features will improve the UI of the website.

![image](https://github.com/user-attachments/assets/cb293e1d-4a95-46d4-a2af-f28dca217ae9)

**Comment by Vignesh025** [comment]
Hey @anishka25 , You can proceed!

**Comment by anishka25** [comment]
Can you also add gssoc-ext label too
