### ISSUE TITLE
[BUG] For security purpose it is necessary to provide the minimum length of password

### ISSUE THREAD

**Issue by Vivan-1045** [VigneshDevHub/CampX#219]
**Describe the bug**
The registration form allows users to create passwords without any minimum length requirement, which can lead to very short and potentially insecure passwords.

**To Reproduce**
1. Go to register
2. After filling the user name and email 
3. Move to password input field

screenshots
![Screenshot (51)](https://github.com/user-attachments/assets/0a890abd-a136-46e2-ae93-5a14bee2d498)
![Screenshot (52)](https://github.com/user-attachments/assets/fecd7b96-6687-412c-9511-ab1c5d95b35a)

**Comment by MuKulsoop** [comment]
Can I work on this ?

**Comment by Vignesh025** [comment]
Hey @Vivan-1045 and @MuKulsoop , someone is already working on this issue. Feel free to explore the project and raise any new issues!
