### ISSUE TITLE
[UI] UI enhancements for register page

### ISSUE THREAD

**Issue by BinaryBhakti** [VigneshDevHub/CampX#22]
issue #2 
**Description**
The UI needs an overall enhancement, focusing on several key areas: changing the background, redesigning the login form, creating a seamless experience between the sign-in and register pages, adjusting the color theme, and ensuring that the page is responsive. These changes aim to improve the visual appeal, usability, and accessibility of the application.

**Current Behavior**
- Background: The current background is plain or not aligned with the brand’s identity, making the interface look less engaging.
- Login Form: The existing form appear outdated, cluttered, or lacks visual hierarchy, making it challenging for users to focus on the main actions.
- Sign In & Register Pages: These pages currently have a disjointed experience, requiring users to navigate through multiple steps or pages without visual consistency.
- Color Theme: The existing color palette is inconsistent, causing confusion or reducing the visual appeal.
- Responsiveness: The UI is not be optimized for different screen sizes, leading to a suboptimal experience on mobile devices.

**Proposed Behavior**
- Background: Update the background to a visually appealing and brand-consistent design, possibly incorporating gradients, imagery, or subtle patterns.
- Login Form: Redesign the login form with a cleaner layout, better spacing, and intuitive input fields. Add visual cues for form validation and make the primary actions (login and submit) more prominent.
- Seamless Sign In & Register Pages: Implement a seamless transition or single-page design for sign-in and registration, such as a toggle or a tab-based interface, ensuring users can switch between the two without navigating away.
- Color Theme: Refine the color scheme to be consistent and harmonious, adhering to brand guidelines. Utilize colors that enhance readability and user engagement.
- Responsiveness: Ensure the layout and elements adjust fluidly across all devices and screen sizes, including desktops, tablets, and smartphones, using responsive design principles.

**Screenshots**
![Campx Sign In_Register page](https://github.com/user-attachments/assets/be9b375e-d936-44aa-9b82-b835fe4b3e56)

**Additional Context**
These changes are aligned with modern design standards and are based on feedback indicating that users find the current UI cluttered and challenging to navigate. The goal is to create a more intuitive and visually pleasing interface that reduces user friction and enhances the overall experience.

**Impact**
- Usability: Enhanced user experience with improved navigation, clearer forms, and a cohesive design.
- Accessibility: Better color contrast and responsive design will make the UI more accessible to a broader range of users.
- Performance: A cleaner design and optimized elements will improve page load times and performance, especially on mobile devices.
- Visual Appeal: A modern, attractive interface will increase user engagement and potentially boost user retention.

**Related Issues**
I can make the whole CampX's website align to  the same theme and concept.

**Comment by Vignesh025** [comment]
Hi @BinaryBhakti ,

Thank you for your detailed proposal! Your suggestions for enhancing the UI are well thought out and align with our goals for improving the user experience in the CampX project.

To ensure a clear and manageable review process, I recommend making separate pull requests for each change. This will allow us to evaluate each enhancement individually and maintain good practices in our workflow.

Looking forward to seeing your contributions!

**Comment by BinaryBhakti** [comment]
Sure
