### ISSUE TITLE
[BUG]: Navbar not visible clearly

### ISSUE THREAD

**Issue by Gaurav075** [VigneshDevHub/CampX#222]
The navbar in home screen is not visible clearly. I make it look clear . Pls assign this issue to me @Vignesh025 
![Screenshot (363)](https://github.com/user-attachments/assets/0460d319-5dc6-4df6-b209-a5de24c56219)

**Comment by Vignesh025** [comment]
Hey @Gaurav075 , Someone is already working on this.
