### ISSUE TITLE
[UI] I want to add a default Avatar for who added this campsight.

### ISSUE THREAD

**Issue by Suvadip-sana** [VigneshDevHub/CampX#223]
**Description**
For now in 'view details' page the owner of this list is not visible in flash.  It mixed with other details and looks like normal as usual. Which is not good for User and also who added this.
**Current Behavior**
Currently it's look like this 
![image](https://github.com/user-attachments/assets/731bf82d-a444-425f-a3dd-0194c6dc8747)

**Proposed Behavior**
But I want to make it like this, Which is more visually appealing
![image](https://github.com/user-attachments/assets/9deac71b-37f5-4871-a36b-6591ff0461da)

**Impact**
It's directly impact in UX of this platform because displaying owner along with it's name is more convenient for user and also very appealing.

Please assign me this issue I want to implement this Feature. Thank you.

**Comment by Vignesh025** [comment]
Hey @Suvadip-sana , You can proceed!
