### ISSUE TITLE
[FEATURE] Feature enhancement of displaying register, log in & log out section in navbar.

### ISSUE THREAD

**Issue by Suvadip-sana** [VigneshDevHub/CampX#224]
**Is your feature request related to a problem? Please describe.**
For now the way your website is displaying the 'Register', 'Log In' & 'Log Out' is not user friendly, It's too simple for now. 
I want to make it  more convenient and visually appealing.

**Describe the solution you'd like**
I want to make this like this.(in recording)   Along with two diff avatar, 1 is when logged in another is when looed out.
It's definitely looks more convenient and user friendly 
 
It's kind of looks like this:

https://github.com/user-attachments/assets/e3e715ac-e0a6-45f9-9260-7b6ccda6009d

**Additional context**
Please assign me this task. It will enhance the UI & UX of this platform.
Add all the necessary points if you assigned me this. Thank you.

**Comment by Vignesh025** [comment]
Hey @Suvadip-sana , Thank you for the suggestion, but we don't need this feature at the moment.
