### ISSUE TITLE
[UI]Wanted to make a unified nav for home and other routes

### ISSUE THREAD

**Issue by omkar861856** [VigneshDevHub/CampX#227]
**Description**
The proposed change in the title will bring uniformity in the look of the app

**Current Behavior**
Different Navbars/UI's for home routes and other routes

**Proposed Behavior**
Home Navbar to other routes

**Screenshots**
Self-implied in the website.

**Additional Context**
#Making the UI better

**Impact**
A more appealing UI/UX

**Related Issues**
#185

I want to work on this - @Vignesh025

**Comment by Vignesh025** [comment]
Hey @omkar861856 , someone is already working on this issue. Feel free to explore the project and raise any new issues!
