### ISSUE TITLE
[UI] Enhancing a custom  Error Page

### ISSUE THREAD

**Issue by sushil-sagar05** [VigneshDevHub/CampX#229]
**Description**
By changing the current ui of error page it becomes user friendly and if user navigates to unusual link then we give them option to redirect to home page for better retention of user on our website

**Current Behavior**
Current UI of Error page needs to be change because it is not user friendly 
![Uploading gssoc3.png…]()

**Comment by Vignesh025** [comment]
Hey @sushil-sagar05 , someone is already working on this issue. Feel free to explore the project and raise any new issues!
