### ISSUE TITLE
[UI] UI enhancements for login page

### ISSUE THREAD

**Issue by BinaryBhakti** [VigneshDevHub/CampX#23]
issue #3 
**Description**
The login page has great potential for enhancement, focusing on key areas such as updating the background, refining the form layout, optimizing the color theme, and ensuring full responsiveness. These improvements will elevate the visual appeal, usability, and accessibility of the login experience, aligning it more closely with the brand's identity and providing a more welcoming and user-friendly interface.

**Current Behavior**
- Background: The current background is simple but could be enhanced to better reflect the brand’s identity, making the login page more vibrant and engaging.
- Login Form: The current form design is functional but could benefit from a cleaner layout, improved spacing, and a more intuitive visual hierarchy to guide users smoothly through the login process.
- Color Theme: The existing color scheme works but could be refined to create a more harmonious and visually appealing look, enhancing the overall experience.
- Responsiveness: While functional, there is room for optimization to ensure the login page adapts seamlessly to various screen sizes, providing an optimal experience across all devices.

**Proposed Behavior**
- Background: Update the background to reflect the brand’s identity better, using elements such as gradients, imagery, or subtle patterns to create a more visually appealing login page.
- Login Form: Redesign the login form with improved spacing, intuitive input fields, and clear form validation. Make the primary actions (login and submit) more prominent and accessible to users.
- Color Theme: Refine the color palette to ensure consistency, readability, and visual appeal, enhancing user engagement and making the login experience more inviting.
- Responsiveness: Implement a fully responsive design for the login page, ensuring the layout and elements adapt fluidly to all screen sizes, including desktops, tablets, and smartphones.

**Screenshots**
![Campx Sign In_Register page](https://github.com/user-attachments/assets/4a27208a-0693-49f3-b9c2-b02013108c6a)

**Additional Context**
These updates are inspired by modern design principles and user feedback, suggesting the login page could be more intuitive and visually appealing. The goal is to create a welcoming and cohesive experience that reduces user friction and makes the login process straightforward and pleasant.

**Impact**
- Usability: A cleaner form layout, clear navigation, and cohesive design will significantly enhance the login experience.
- Accessibility: Better color contrast and a responsive design will make the login page accessible to a broader range of users, including those with visual impairments.
- Performance: Streamlined design elements will improve page load times, particularly on mobile devices, providing a faster login experience.
- Visual Appeal: A refreshed and modernized login page will create a strong first impression and may increase user engagement and retention.
- The UI of the login page and the register page will be interlinked.(I have also raised a issue for that)

**Related Issues**
This approach can be applied to other pages within the application to ensure a consistent and professional appearance across the entire CampX website.

**Comment by Vignesh025** [comment]
Hi @BinaryBhakti ,

Thank you for your detailed proposal! Your suggestions for enhancing the UI are well thought out and align with our goals for improving the user experience in the CampX project.

To ensure a clear and manageable review process, I recommend making separate pull requests for each change. This will allow us to evaluate each enhancement individually and maintain good practices in our workflow.

Looking forward to seeing your contributions!

**Comment by BinaryBhakti** [comment]
Sure
