### ISSUE TITLE
[UI] Campground's Page needs some modification

### ISSUE THREAD

**Issue by itsadi-24** [VigneshDevHub/CampX#231]
ISSUE 1:-
![Screenshot 2024-10-19 162559](https://github.com/user-attachments/assets/f08f3394-0878-4c14-8cf7-ffbed2f07c9b)
i want to make the cards in a grid format because each card is unnecessarily taking the full width which is not required, by making it in a 2column grid view the user can get more info at once without having him to scroll.

ISSUE 2:-
![Screenshot 2024-10-19 162430](https://github.com/user-attachments/assets/765fb5c2-5de7-4aad-a361-f5ea504c2624)
As you can see its not properly responsive, the image width is shorter than that of card.

I would like to fix those issues and also improve its appearance.

**Comment by Vignesh025** [comment]
Hey @itsadi-24 , You can proceed!

**Comment by Vignesh025** [comment]
Hey @itsadi-24 , are you working on this?

**Comment by itsadi-24** [comment]
Hi @Vignesh025 sorry for the delay,was having exams,will complete it by EOD.

**Comment by Vignesh025** [comment]
@itsadi-24 No worries! I was just checking in. Good luck with your exams!

**Comment by itsadi-24** [comment]
Hi @Vignesh025 i have almost done it,but due to some unknown issues,i am facing some bugs.
Firstly for some reasons my map is not being rendered(have checked the updated code with old code,no issue here)
Secondly the images are not being rendered.
![Screenshot 2024-11-01 104521](https://github.com/user-attachments/assets/16a0c398-921f-4340-8899-ed5eb636780f)
![Screenshot 2024-11-01 104505](https://github.com/user-attachments/assets/c02d3cce-535b-495a-a510-2f9a2d179907)
I tried everything from last 2 days but nothing seemed to workout.

**Comment by Vignesh025** [comment]
@itsadi-24 , Sync your fork and make a PR. We'll look into it.

**Comment by itsadi-24** [comment]
done #359  .Do check and tell if i need to do anything.
