### ISSUE TITLE
[DOC]  improve readme file documentation

### ISSUE THREAD

**Issue by EfrataAron** [VigneshDevHub/CampX#234]
## Description

Please provide a clear and concise description of the issue or suggestion related to the documentation. Include details about where the issue is found or what needs to be added or improved.

i would like to improve the appearance of the readme file. please assign it to me.
**Affected Pages**:
- [ yes] README.md
- [ ] Installation Guide
- [ ] Configuration Guide
- [ ] Other (please specify)

## Type of Documentation Change

- [yes ] Update existing documentation
- [yes ] Add new documentation
- [ ] Remove outdated or redundant documentation
- [ ] Other (please specify)

## Additional Context

Please add any other context or screenshots about the documentation issue or suggestion here.

## Suggested Improvements

If applicable, suggest how the documentation could be improved. This could include rewording, adding examples, clarifying instructions, etc.

---

**Comment by Vignesh025** [comment]
Hey @EfrataAron, someone is already working on this issue. Feel free to explore the project and raise any new issues!
