### ISSUE TITLE
[DOC] Updation of contributing.md file

### ISSUE THREAD

**Issue by Nikhil0-3** [VigneshDevHub/CampX#239]
File needs to be in following way

Wanted to do the following changes :-

How to contribute (fix bugs, add features)
Steps for submitting changes
Project setup instructions
Rules for code style
Code of conduct for respectful behavior
Enhance the project structure
Add the help and support section
Add the pull request section
Add issue report process section

Also, by adding some symbols file looks more creative.

**Comment by Vignesh025** [comment]
Hey @Nikhil0-3 , someone is already working on this issue. Feel free to explore the project and raise any new issues!
