### ISSUE TITLE
[FEATURE] Improvement of flash message.

### ISSUE THREAD

**Issue by Suvadip-sana** [VigneshDevHub/CampX#242]
**Is your feature request related to a problem? Please describe.**
For now the flash message is displaying using bootstrap simple alert message. Particularly for this there is an ISSUE, that it's not automatically disappeared, need to manually close it or after refresh the page for closing this, and it's directly placed on the webpage as content which is very annoying and directly effect to the UX.
And also the flash message displaying very largely at the top of the screen with big size. That effect the UI of the Web site.
The Issue is here --->
![image](https://github.com/user-attachments/assets/f9eb8147-d2b2-4a32-aaf8-34ea8c33e6a1)

**Describe the solution you'd like**
I want to replace this flash message with Bootstrap Toasts. For this the advantage is, it disappeared automatically after 5 second, There is also an option to close it by clicking the cross button on it, which is impact the User Experience directly because it's not directly placed on the website content, Just appeared on the screen corner and disappeared automatically, like normal modern website looks like.
Like this -->

https://github.com/user-attachments/assets/f27d3f9e-00b6-46d9-9885-beab266276a6

**Additional context**
@Vignesh025  I raised this ISSUE at the beginning, But you tell someone work on this. #124 Now I see this is remain same.
Please assign me this task. I want to implement this. Because your existing flash msg is not looks like professional,/modern website.

**Comment by Suvadip-sana** [comment]
@Vignesh025  tell me about this.

**Comment by Suvadip-sana** [comment]
@Vignesh025 Please tell me what you think.

**Comment by Vignesh025** [comment]
@Suvadip-sana , You can proceed!
