### ISSUE TITLE
[UI] New Campground's page needs some modification

### ISSUE THREAD

**Issue by itsadi-24** [VigneshDevHub/CampX#244]
![Screenshot 2024-10-20 175604](https://github.com/user-attachments/assets/f92f55a1-3dbe-441c-a310-a8c5e0de856e)

I want to improve its looks
also add the tags hacktoberfest-accepted and gssoc-ext

**Comment by Vignesh025** [comment]
Hey @itsadi-24 , You can proceed!

**Comment by itsadi-24** [comment]
@Vignesh025 Done! you can check PR #252
