### ISSUE TITLE
JWT Authentication for signup and signin

### ISSUE THREAD

**Issue by udayempire** [VigneshDevHub/CampX#245]
As I gone through your project I see there is no Authentication for signup and Signin and there are multiple authorization Techniques while I would like to contribute with JWT.

**Description of the solution**
Adding JWT (JSON Web Token) to a website is important for handling authentication and authorization in a secure and efficient manner.

This will help having secure authentication and you can also pass valuable informations like username,email with the middleware to use in your frontend.

How I will Implement-
1.I will create a middleware.js for user and admin inside a middleware folder.

Please assign me to work on this issue and add gssoc and hacktoberfest labels in it.

**Comment by bullseye4703** [comment]
Hey, I would love to contribute to this issue. So, please assign this to me.

**Comment by Vignesh025** [comment]
We don't need this feature right now, but thanks for the suggestion!
