### ISSUE TITLE
[UI] Enhance the ui of campgrounds list on All Campgrounds page

### ISSUE THREAD

**Issue by AdityaInnovates** [VigneshDevHub/CampX#253]
**Description**
Enhance the UI of the campgrounds list displayed on the "All Campgrounds" page. The goal is to improve visual appeal and usability by refining the layout, styling, and interaction design, making it more user-friendly and aesthetically pleasing.

**Current Behavior**
The campgrounds list currently appears as a simple grid with minimal styling. Each campground card displays basic information like the name, image, and a brief description, but lacks spacing, consistent card sizes, and visual hierarchy, making it look cluttered and difficult to scan.

**Proposed Behavior**
The updated UI will feature a more modern card layout with consistent sizes, improved spacing between elements, and enhanced typography. Each card will include a prominent image, campground name, description, and a call-to-action button for more details. The cards will be more responsive and have hover effects to highlight interactivity. Additionally, a filter sidebar will be added to allow users to quickly refine their search.

**Screenshots**
<img width="1512" alt="Screenshot 2024-10-21 at 5 14 46 PM" src="https://github.com/user-attachments/assets/8c18f5e1-9600-4b22-a9dd-45a3e4073ccc">

**Additional Context**

The new design follows Material Design principles for card layouts, ensuring a familiar and intuitive user experience.
User feedback has indicated a desire for better visuals and easier navigation through the campground listings.
The updated design is inspired by popular travel and booking platforms to align with user expectations.

**Impact**
This change will significantly improve the usability of the "All Campgrounds" page by making it easier for users to browse and select campgrounds. It will enhance the visual appeal, potentially increasing user engagement and reducing bounce rates. The addition of filtering options will also streamline the search process for users.

**Related Issues**
- https://github.com/VigneshDevHub/CampX/issues/115

**Comment by Vignesh025** [comment]
Hey @AdityaInnovates , someone is already working on this issue. Feel free to explore the project and raise any new issues!
