### ISSUE TITLE
[FEATURE] Convert images to webp format

### ISSUE THREAD

**Issue by Gauravtb2253** [VigneshDevHub/CampX#255]
**Is your feature request related to a problem? Please describe.**
Png images are little slower to load

**Describe the solution you'd like**
I would like to change images to webp format
Webp images are faster to load and offer optimization

**Comment by Vignesh025** [comment]
Hey @Gauravtb2253 , someone is already working on this issue. Feel free to explore the project and raise any new issues!

**Comment by Gauravtb2253** [comment]
do you have any specific issue that I can solve

**Comment by Vignesh025** [comment]
@Gauravtb2253, we don't have any specific issues to be solved as of now.
