### ISSUE TITLE
[FEATURE] Adding dynamic search feature

### ISSUE THREAD

**Issue by Gauravtb2253** [VigneshDevHub/CampX#256]
**Is your feature request related to a problem? Please describe.**
Currently when we want to search we need to enter the query and then we get the results

**Describe the solution you'd like**
I would like to add dynamic search feature where in the search results will be filtered as soon as the user starts typing
It will increase the user experience

**Comment by Vignesh025** [comment]
Hey @Gauravtb2253 , you can proceed!

**Comment by Gauravtb2253** [comment]
Can you pls add level3 label
It would be nice if you add it 
Thank you

**Comment by Vignesh025** [comment]
No, we are only supposed to add level 3 to certain issues. However, after you make your PR, we will review the code changes and decide based on them. So don't worry!

**Comment by haseebzaki-07** [comment]
@Vignesh025 Can I take this issue! It's here for long.

**Comment by Vignesh025** [comment]
@haseebzaki-07 , this issue is completed
