### ISSUE TITLE
[UI]new campground form  

### ISSUE THREAD

**Issue by MaahiVaghela** [VigneshDevHub/CampX#257]
**Description**
 new campground form doesn't match theme . So I want to change it . Please assign this issue to me

![image](https://github.com/user-attachments/assets/5907c4f5-402a-4f1c-a1de-24cbff22164f)

**Comment by Vignesh025** [comment]
Hey @MaahiVaghela , someone is already working on this issue. Feel free to explore the project and raise any new issues!
