### ISSUE TITLE
[UI] Edit Campground page enhancement

### ISSUE THREAD

**Issue by itsadi-24** [VigneshDevHub/CampX#261]
![Screenshot 2024-10-22 024153](https://github.com/user-attachments/assets/00c7ed33-3f2f-473a-8830-1762dc8cd7fa)
i want to improve its ui,also add label hacktoberfest-accepted and gssoc-ext

**Comment by Vignesh025** [comment]
Hey @itsadi-24 , You can proceed!

**Comment by itsadi-24** [comment]
Hi @Vignesh025  pls check PR #279
