### ISSUE TITLE
[UI] Improve the capmgrounds page resposiveness for mobile devices

### ISSUE THREAD

**Issue by roushan-code** [VigneshDevHub/CampX#264]
## Describe the bug
- Capmgrounds page is not resposiveness for mobile devices and tablet devies.

**Screenshots**
![camp-res](https://github.com/user-attachments/assets/85e8ad6b-e3ed-404e-82cd-ab6d35664076)

**Expected behavior**
- Capmgrounds page should responsive for all devices.

## Demo video
![2024-10-2212-14-32-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/483957de-a6b0-452d-aa12-23ab326ef18c)

i want to improve its ui,also add label hacktoberfest-accepted and gssoc-ext

**Comment by Vignesh025** [comment]
Hey @roushan-code , you can proceed!

**Comment by roushan-code** [comment]
Hey @Vignesh025, you haven't assigned me yet.?
