### ISSUE TITLE
Add 'About' Section with Navbar Integration

### ISSUE THREAD

**Issue by TanyaaSrivastava** [VigneshDevHub/CampX#267]
1. The project lacks an 'About' section that provides users with information about the website and its features. This section should offer a clear overview of the purpose of the site, its key functionalities, and any relevant details that help users understand the value it offers.

2. To improve accessibility and visibility, instead of placing the 'About' section at the bottom of the page, a separate heading should be included in the navbar. This heading will link to a dedicated 'About' page or section, allowing users to easily navigate to it from any part of the website.

**Comment by Vignesh025** [comment]
Hey @TanyaaSrivastava  , We don't need this feature right now, but thanks for the suggestion!
