### ISSUE TITLE
[FEATURE] Improve the UI of the campground cards

### ISSUE THREAD

**Issue by Himanshu-kumar025** [VigneshDevHub/CampX#268]
There UI  of this card is not that good the card should not  be formed that long width . I like to recreate the cards under GSSOC'24 and Hacktofest'24
thank you

![Screenshot 2024-10-22 183028](https://github.com/user-attachments/assets/89a65bab-cb56-4d30-959c-32e8a1bccea0)

**Comment by Vignesh025** [comment]
Hey @Himanshu-kumar025 , someone is already working on this issue. Feel free to explore the project and raise any new issues!
