### ISSUE TITLE
Footer social media handles

### ISSUE THREAD

**Issue by Sneharaj7645653** [VigneshDevHub/CampX#270]
**Describe the bug**
The links to the social media handles open on the same tab.

**To Reproduce**
1. Go to footer of the campground page.
2. Click on icon of any social media handle.
3. See error

**Expected behavior**
The link should ideally open on a new tab.

**Screenshots**

**Desktop (please complete the following information):**
 - Applicable for all.
**Smartphone (please complete the following information):**
 - Applicable for all.

**Comment by Vignesh025** [comment]
Hey @Sneharaj7645653 , You've closed the PR.

**Comment by Sneharaj7645653** [comment]
May you please have a look at it now.
