### ISSUE TITLE
Improve Code Documentation and Structure for Mapbox Integration

### ISSUE THREAD

**Issue by Sumanth077s** [VigneshDevHub/CampX#272]
The current implementation of the Mapbox integration code lacks comprehensive documentation and structured formatting, which makes it difficult to understand and maintain. This issue aims to enhance the code by:

Adding Detailed Comments: Provide meaningful explanations for key sections of the code, including the purpose of each function, the configuration options used, and the data transformations performed.

Improving Code Formatting: Ensure consistent indentation, spacing, and overall readability to facilitate easier navigation through the code.

Implementing Helper Functions: Refactor repetitive code segments, such as popup management, into helper functions to reduce redundancy and improve code maintainability.

Utilizing Destructuring: Use object destructuring for cleaner access to properties within objects, enhancing code clarity.

Error Handling: Ensure that the code gracefully handles potential errors, particularly during the cluster expansion zoom feature.

By addressing these points, the code will become more user-friendly for developers, making it easier to implement future enhancements or troubleshoot issues as they arise.

**Comment by Vignesh025** [comment]
Please work on an issue only after you have been assigned to it. Thanks!
