### ISSUE TITLE
[FEATURE]: Add google login frontend

### ISSUE THREAD

**Issue by NK-Works** [VigneshDevHub/CampX#278]
**Is your feature request related to a problem? Please describe.**
I want to add the option to google login 

**Describe the solution you'd like**
The frontend will send the access_token to the backend which will then work on it and allow the user to login with google

![image](https://github.com/user-attachments/assets/8bb3350e-744a-4c91-ac6c-af6d9b51d3d5)

**Comment by Vignesh025** [comment]
Hey @NK-Works , We don't need this feature right now, but thanks for the suggestion!
