### ISSUE TITLE
Improve Campgrounds page

### ISSUE THREAD

**Issue by shubhagarwal1** [VigneshDevHub/CampX#281]
**Changes to be made** 
-fix the searchbar to the top 
- improve page designing 
- improve card designing 
<img width="1411" alt="Screenshot 2024-10-23 at 7 23 23 AM" src="https://github.com/user-attachments/assets/988730d3-3490-407d-9c42-be68a0a700b2">

**Comment by Vignesh025** [comment]
Hey @shubhagarwal1 , someone is already working on this issue. Feel free to explore the project and raise any new issues!

**Comment by shubhagarwal1** [comment]
> Hey @shubhagarwal1 , someone is already working on this issue. Feel free to explore the project and raise any new issues!

hey @Vignesh025 can you please assign me this task as discussed i will make changes
