### ISSUE TITLE
[DOC] add hacktoberfest and gssoc banner to readme file

### ISSUE THREAD

**Issue by agarwalbhargavi** [VigneshDevHub/CampX#288]
## Description
i would like to add hacktoberfest and gssoc banner to the readme file.
it would look like this
<img width="676" alt="Screenshot 2024-10-24 013452" src="https://github.com/user-attachments/assets/00fd9af5-27ec-41d1-a5a5-c4a9a5099a68">

**Affected Pages**:
- [x] README.md

## Type of Documentation Change
- [x] Add new documentation

@Vignesh025 kindly assign me this issue

**Comment by Balamurugan-cyber** [comment]
please assign this issue

**Comment by Vignesh025** [comment]
Hey @agarwalbhargavi , We don't need this feature right now, but thanks for the suggestion
