### ISSUE TITLE
[FEATURE] Implement Carousel for User Testimonial at home page

### ISSUE THREAD

**Issue by IkkiOcean** [VigneshDevHub/CampX#289]
### Description

We need to implement a carousel component to display user testimonials on the homepage. This will enhance the user experience by allowing visitors to easily browse through reviews without overwhelming them with too much information at once.

### demo video:

https://github.com/user-attachments/assets/26637401-25c2-4f2a-a769-0b6e647c897d

I will implement it considering the UI of CampX

### It should be implemented because

- Enhanced User Experience
A carousel provides a visually appealing way to display reviews, making it easier for users to engage with feedback without feeling overwhelmed by information.

- Highlighting Positive Feedback
A carousel can be used strategically to showcase particularly glowing reviews, building trust and credibility for the brand or product.

**Comment by Vignesh025** [comment]
Hey @IkkiOcean , We don't need this feature right now, but thanks for the suggestion.
