### ISSUE TITLE
[FEATURE] Filters for campgrounds

### ISSUE THREAD

**Issue by Saagar2005** [VigneshDevHub/CampX#29]
It would be nice to have filters on the campgrounds page. A user must be able to filter by cost, for example. It would also be nice to have a search bar.  We can also maintain the number of reviews or the average rating for a campground. A user must be able to filter by such a parameter as well.
This makes it really useful for the user, especially when a large number of campgrounds have been listed before him.

I would like to implement these. Kindly assign it to me.

**Comment by Vignesh025** [comment]
@Saagar2005, That's a really good idea! I'm assigning this issue to you. Please make separate pull requests for each change and ensure to sync the fork often to stay up-to-date with the latest changes

**Comment by Vignesh025** [comment]
Hey @Saagar2005 , are you still working on this issue? If not, please let me know so I can assign it to someone else. Thanks!
