### ISSUE TITLE
 Enhancing the contributor Section and Structuring

### ISSUE THREAD

**Issue by alo7lika** [VigneshDevHub/CampX#294]
## Description

The goal is to enhance the Contributor section of the README and improve its structure for better clarity and presentation. This may involve updating contributor information, adding images or badges, and reformatting the layout for better readability.

**Affected Pages**:
- [x] README.md
- [ ] Installation Guide
- [ ] Configuration Guide
- [ ] Other (please specify)

## Type of Documentation Change

- [x] Update existing documentation
- [ ] Add new documentation
- [ ] Remove outdated or redundant documentation
- [ ] Other (please specify)

## Additional Context

The current Contributor section may lack visual appeal or sufficient organization. A more structured and visually engaging layout can highlight the contributions of individuals more effectively. Possible suggestions could include adding badges, aligning contributor details, or grouping by contribution types. If applicable, screenshots can be shared to show the before and after state of the Contributor section for reference.

## Suggested Improvements

- **Reformat Contributor Section**: Use a grid layout to make the section visually appealing and organized.
- **Add Images**: Display contributor GitHub avatars with a consistent size.
- **Include Links**: Add links to each contributor's GitHub profile directly.
- **Use Badges**: Include badges that showcase contributions such as "Maintainer," "Top Contributor," or specific GitHub activity (stars, forks).
- **Group Contributors**: Categorize contributors based on the type of contribution (e.g., code, documentation, design).
- **Include Automation**: Consider using GitHub tools like `all-contributors` to automate the addition and maintenance of contributors.

---

Feel free to tweak any part based on your specific requirements!

**Comment by alo7lika** [comment]
ADD GSSOC EXT 24 AND HACKTOBERFEST AND assign me this task @Vignesh025

**Comment by Vignesh025** [comment]
Hey @alo7lika , you can proceed!

**Comment by alo7lika** [comment]
> Hey @alo7lika , you can proceed!

assign me as well as add labels GSSOC EXT 24 AND HACKTOBERFEST
