### ISSUE TITLE
Enhanced Footer with Social Links ON README

### ISSUE THREAD

**Issue by alo7lika** [VigneshDevHub/CampX#295]
## Description

The task involves enhancing the footer of the README with social media links for better community engagement and visibility. This enhancement aims to make it easier for contributors and users to connect via various social platforms related to the project.

**Affected Pages**:
- [x] README.md
- [ ] Installation Guide
- [ ] Configuration Guide
- [ ] Other (please specify)

## Type of Documentation Change

- [x] Update existing documentation
- [ ] Add new documentation
- [ ] Remove outdated or redundant documentation
- [ ] Other (please specify)

## Additional Context

Currently, the README might not include a dedicated footer with social media links, making it less engaging. Adding social media links (e.g., GitHub, Twitter, LinkedIn) will provide a more comprehensive guide and allow contributors and users to follow the project's updates, contribute, or reach out for support. This change will enhance the visibility of the project and connect with the community more effectively.

## Suggested Improvements

- **Add Social Media Icons**: Use recognizable icons for each social platform (e.g., GitHub, Twitter, LinkedIn) with clickable links.
- **Positioning**: Place the social links in a dedicated footer section at the bottom of the README for consistency and easy access.
- **Use Badges**: Consider using markdown badges with links to specific social media profiles, repositories, or project-specific hashtags.
- **Design Consistency**: Keep the style of the footer consistent with the rest of the README, using similar fonts, colors, and alignment.
- **Include a Call to Action**: Add a small message encouraging readers to follow, star, or contribute to the project, with links to the relevant social platforms.

---

Let me know if any other details need to be included!

**Comment by alo7lika** [comment]
ADD LABELS GSSOC EXT 24 AND HACKTOBERFEST AND ASSIGN ME THIS TASK @Vignesh025 
Thank you!

**Comment by alo7lika** [comment]
> ADD LABELS GSSOC EXT 24 AND HACKTOBERFEST AND ASSIGN ME THIS TASK @Vignesh025 Thank you!

@Vignesh025

**Comment by Vignesh025** [comment]
Hey @alo7lika , you can proceed!
