### ISSUE TITLE
[UI] : Campgrounds page CARDS 

### ISSUE THREAD

**Issue by AADESHak007** [VigneshDevHub/CampX#298]
**Description**
I want to redesign the cards in the CAAMPGROUNDS PAGE of your website  . 

**Current Behavior**
The color scheme is can improved and the design of the cards can be changed .
There are few cards which are incomplete . 
I would like make changes to the color scheme and want redesign the page a bit  .
Please assign this issue to me .

**Screenshots**
![Screenshot 2024-10-25 122931](https://github.com/user-attachments/assets/5401a5b5-db72-497c-a0be-67caad45a57e)
![Screenshot 2024-10-25 122917](https://github.com/user-attachments/assets/8b062be8-5f30-49c9-9102-fbf5022415e8)

**Related Issues**
Link to any related issues, discussions, or feature requests that are relevant to this UI change.

**Comment by Vignesh025** [comment]
Hey @AADESHak007 , We don't need this feature right now, but thanks for the suggestion.
