### ISSUE TITLE
[FEATURE] Implementing oAuth like google,twitter and github

### ISSUE THREAD

**Issue by Edasgh** [VigneshDevHub/CampX#299]
I want to add oauth using google, twitter & github in the login & register page
I would like to work on this issue.
Please assign this issue to me under gssoc-ext, hacktoberfest-accepted and a relevant level labels

##Screenshots
Like this
![Screenshot 2024-10-25 131800](https://github.com/user-attachments/assets/5ed9d0f9-fcba-49df-bf7a-71cc31b35b7e)

**Comment by Vignesh025** [comment]
Hey @Edasgh , We don't need this feature right now, but thanks for the suggestion.
