### ISSUE TITLE
[UI] UI change for Login Page

### ISSUE THREAD

**Issue by Vignesh025** [VigneshDevHub/CampX#3]
**Description**
Improve the UI of Login page to be more attractive

**Current Behavior**
The current UI is minimalist.

*If you're going to work on this issue, create a new issue explaining your changes and mention this issue.*

**Comment by villAsh** [comment]
Hello @Vignesh025,
I would like to work on this,
can you please assign this to me under Hacktoberfest.

**Comment by Vignesh025** [comment]
Hi @villAsh ,

Could you please create a new issue outlining all the specific changes you intend to make? Additionally, kindly reference this issue (issue #3) in the body of the new issue you create.

Thank you!

**Comment by BinaryBhakti** [comment]
I want to work on this issue. Please assign this issue to me.

**Comment by Vignesh025** [comment]
Hey @BinaryBhakti , Create a new issue stating all the changes you want to make and mention this issue like (issue #3). I'll review it and assign it to you.

**Comment by aditi13y** [comment]
Hi there,please assign this issue to me.

**Comment by Vignesh025** [comment]
Hey @aditi13y , Create a new issue stating all the ideas that you have in improving the UI for the login page. I'll assign it to you.

**Comment by Vignesh025** [comment]
Hey @aditi13y , Are you working on this issue?

**Comment by itsadi-24** [comment]
Hi @Vignesh025  can you assign me this issue i will make PR within a day. Thanks!

**Comment by Vignesh025** [comment]
@itsadi-24 , you can proceed.

**Comment by itsadi-24** [comment]
Yes i'm working on it

**Comment by itsadi-24** [comment]
@Vignesh025 i have submitted my PR
