### ISSUE TITLE
[UI] Design Eye-Catching Progress Bar for UI aesthetics

### ISSUE THREAD

**Issue by Edasgh** [VigneshDevHub/CampX#300]
**Screenshots**
Like this
![Screenshot 2024-10-25 132130](https://github.com/user-attachments/assets/dcf2410d-3bd0-4c84-9b6d-ea2bae3ca0b7)

 **Proposed Behavior** :
- Enhanced Usability: A visually appealing progress bar helps users understand their progress within a task or process improving usability and navigation.

- Improved Aesthetics: Customizing the  progress bar  to match the UI enhances the overall look and feel of the application, making it more attractive to users.

- Increased User Engagement: An engaging and cohesive interface can lead to higher user satisfaction, encouraging them to interact more with the application.

Please assign this issue to me under gssoc-ext, hacktoberfest-accepted and a relevant level labels

**Comment by Vignesh025** [comment]
Hey @Edasgh ,We don't need this feature right now, but thanks for the suggestion.
