### ISSUE TITLE
color changes in sigin and login pages

### ISSUE THREAD

**Issue by Sivasaiklu** [VigneshDevHub/CampX#303]
![image](https://github.com/user-attachments/assets/63b416bb-44ab-4162-b907-bdb30f688f5f)

![image](https://github.com/user-attachments/assets/626bd538-2fe2-486e-adba-6c8549d7caa6)

> register and signin links are not visible clearly

**Comment by Vignesh025** [comment]
Hey @Sivasaiklu , We’re happy with the colors! You can, however, work on adjusting the background image to improve font visibility.

**Comment by Sivasaiklu** [comment]
ok i am closing this issue
