### ISSUE TITLE
 Interactive Campground Dot Click with Card Display💫

### ISSUE THREAD

**Issue by charmi2109** [VigneshDevHub/CampX#304]
Enable a card display with an image of the campground when clicking on any dot(hovering on any dot  representing a campground). This feature will make the website more visually appealing and intuitive, allowing users to see camp details at a glance.

![image](https://github.com/user-attachments/assets/55a64f82-0ec8-4290-9ea7-1468a75f0c19)

please assign me this issue @Vignesh025 under gsoc-ext ,enhancement and relevant tags!

**Comment by Vignesh025** [comment]
Hey @charmi2109 , We’re happy with the colors! You can, however, work on adjusting the background image to improve font visibility.

**Comment by Vignesh025** [comment]
Hey @charmi2109 , We don't need this feature right now, but thanks for the suggestion.
