### ISSUE TITLE
[FEATURE]: Subscribe us

### ISSUE THREAD

**Issue by haseebzaki-07** [VigneshDevHub/CampX#306]
**Is your feature request related to a problem? Please describe.**
Add subscribe us feature to the website.

**Describe the solution you'd like**
Users filling in the valid mail ids receive a confirmation mail to their mail ids for successful subscription.
Create backend API and the frontend component if not present.

**Comment by Vignesh025** [comment]
Hey @haseebzaki-07 ,We don't need this feature right now, but thanks for the suggestion
