### ISSUE TITLE
[UI] UI enhancements for the campgrounds page

### ISSUE THREAD

**Issue by BinaryBhakti** [VigneshDevHub/CampX#31]
issue #6 
### **Description**
The proposed UI changes involve updating the layout, map, color scheme, text, and fonts across the interface. These modifications aim to enhance the visual appeal, improve readability, and align the design with modern UI trends, resulting in a more cohesive user experience.

### **Current Behavior**
The current UI suffers from an outdated layout, inconsistent color scheme, and fonts that are less readable. The map element is not well integrated with the overall design, and the text styling doesn't align with the visual identity.

### **Proposed Behavior**
The updated UI will feature a more structured layout with a modern, user-friendly map design. The new color scheme will improve contrast and visual appeal, while updated fonts will enhance readability. The revised text formatting will align with the updated visual style, creating a more cohesive and pleasant user experience.

### **Screenshots/Mockups**
![All campgrounds](https://github.com/user-attachments/assets/5617a229-1b2a-4622-88ed-afa96e457fd1)

### **Additional Context**
These changes are informed by recent design guidelines, user feedback highlighting issues with readability and layout, and best practices from similar applications. Accessibility considerations have also been taken into account for color contrast and font choice.

### **Impact**

- Usability: The clearer layout, modern typography, and improved text placement enhance readability and ease of navigation, making the login and registration process smoother.
- Visual Appeal: The addition of gradients, refined text sizing, and polished form elements elevates the overall aesthetic of the UI, making a strong first impression on users.
- Accessibility: By ensuring better readability, contrast, and responsiveness, the redesign caters to a wider range of users, including those with visual impairments.
- Performance: A more streamlined design with modern elements can improve loading times, especially on mobile devices, leading to a more efficient and responsive experience.

### **Related Issues**
This proposal complements ongoing discussions about UI consistency across the CampX platform, ensuring that design standards and visual appeal are maintained throughout. Additionally, it addresses user feedback regarding the need for better accessibility and visual coherence across devices.

**Comment by Vignesh025** [comment]
@BinaryBhakti , Thank you for the update! Everything looks good, but the cluster map is mandatory, so please make sure not to remove it. Also, it would be great if you could improve the navbar for better usability. Looking forward to the changes!

**Comment by BinaryBhakti** [comment]
Ok, I will work upon these changes, and do provide you with the changes.

**Comment by BinaryBhakti** [comment]
So I have made some changes with the UI as you mentioned, 
Updated one below:

![Screenshot 2024-09-30 222337](https://github.com/user-attachments/assets/af7379a0-98b3-4569-8619-f603e3b9cf34)


So if you want more changes, I am open for it.

**Comment by Vignesh025** [comment]
Hey @BinaryBhakti , I'm happy with the one on the right side. but change the text on the button from "Continue" to "View".

**Comment by BinaryBhakti** [comment]
Yes, Sure

**Comment by BinaryBhakti** [comment]
You haven't assigned me this issue. Could you assign me?

**Comment by Vignesh025** [comment]
@BinaryBhakti , I've assigned it to you!
