### ISSUE TITLE
[DOC]  Enhancements in code of conduct file 

### ISSUE THREAD

**Issue by Nikhil0-3** [VigneshDevHub/CampX#314]
## Description

I want to add following points- 
Our Pledge
Our Standards
Enforcement Responsibilities
Scope
Pull Request Guidelines
Enforcement
Enforcement Guidelines
Attribution
Conclusion.

**Affected Pages**:
- [ ] README.md
- [ ] Installation Guide
- [ ] Configuration Guide
- [ x] Other (please specify) - code of conduct.md 

## Type of Documentation Change

- [ x] Update existing documentation
- [ ] Add new documentation
- [ ] Remove outdated or redundant documentation
- [ ] Other (please specify)

## Additional Context

Please add any other context or screenshots about the documentation issue or suggestion here.

## Suggested Improvements

If applicable, suggest how the documentation could be improved. This could include rewording, adding examples, clarifying instructions, etc.

---
here I added the screenshots of the file on which I worked earlier

![Screenshot 2024-10-22 104423](https://github.com/user-attachments/assets/c0bf4699-9d36-40f8-bade-82f80e29c291)
![Screenshot 2024-10-22 104433](https://github.com/user-attachments/assets/0e87d657-973a-465f-8245-91e37358f483)
![Screenshot 2024-10-22 104442](https://github.com/user-attachments/assets/a0737644-fa41-43d5-8f83-9df72271a176)

**Comment by Vignesh025** [comment]
Hey @Nikhil0-3 , you can proceed!
