### ISSUE TITLE
[FEATURE] Add follow us section

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [VigneshDevHub/CampX#315]
**Is your feature request related to a problem? Please describe.**
Add follow us section
**Describe the solution you'd like**
Add follow us section
**Describe alternatives you've considered**

**Additional context**

**Comment by Vignesh025** [comment]
Hey @KapuluruBhuvaneswariVspdbct , We don't need this feature right now, but thanks for the suggestion.
