### ISSUE TITLE
[FEATURE]Add cursor animation

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [VigneshDevHub/CampX#316]
**Is your feature request related to a problem? Please describe.**
Add cursor animation
**Describe the solution you'd like**
Add cursor animation
**Describe alternatives you've considered**

Add cursor animation

**Comment by Vignesh025** [comment]
Hey @KapuluruBhuvaneswariVspdbct , We don't need this feature right now, but thanks for the suggestion.
