### ISSUE TITLE
[FEATURE]Add blog page

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [VigneshDevHub/CampX#317]
**Is your feature request related to a problem? Please describe.**
Add blog page

**Describe the solution you'd like**
Add blog page
**Describe alternatives you've considered**
Add blog page
**Additional context**

**Comment by Vignesh025** [comment]
Hey @KapuluruBhuvaneswariVspdbct , We don't need this feature right now, but thanks for the suggestion.
