### ISSUE TITLE
🚀 Automate Connections with GitHub Actions!

### ISSUE THREAD

**Issue by amiya-cyber** [VigneshDevHub/CampX#336]
We can implement github workflows for the following things:

Auto comment on issue Closed and Opened
Auto comment on PR mergs
Auto comment on PR raises
Using this workflows makes you'r repo more interactive !

please assign me and i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label
@Vignesh025

**Comment by Vignesh025** [comment]
Does the auto comment works all the time or for only the users who raised the issue or PR for the first time?

**Comment by amiya-cyber** [comment]
all the time

**Comment by Vignesh025** [comment]
How many workflow files are you gonna create?

**Comment by amiya-cyber** [comment]
ok done @Vignesh025 can you assign me
