### ISSUE TITLE
Overflowing Reviews Section

### ISSUE THREAD

**Issue by shar2710** [VigneshDevHub/CampX#341]
**Description**
Currently, as more reviews are added, the page height increases significantly. This can lead to a poor user experience, especially on smaller screens.

**Current Behavior**
The reviews section should have a scrollable container that allows users to view all reviews without increasing the overall page height.

**Screenshots**
![image](https://github.com/user-attachments/assets/dcc70d0b-552a-4bc5-ae8f-044920c566c2)

**Additional Considerations**
 Consider implementing a mechanism to limit the number of reviews displayed initially and load more on demand using JavaScript.

Please assign  me with this
@Vignesh025

**Comment by Vignesh025** [comment]
@shar2710 you can proceed!

**Comment by Sourabh782** [comment]
@Vignesh025 i see you reopened this issue? if its available can i work on it?

**Comment by Vignesh025** [comment]
@Sourabh782 , you can proceed!
