### ISSUE TITLE
[UI]:Enhancement in the ui of campground page

### ISSUE THREAD

**Issue by RaviP9973** [VigneshDevHub/CampX#346]
**Description**
I can enhance the ui of the this page 

**Current Behavior**

![image](https://github.com/user-attachments/assets/93b0d138-2ca7-4b7c-a9a1-aa7515338423)

current ui is not that appealing i want to enhace the ui 

**Impact**
better user experience
**Related Issues**
Link to any related issues, discussions, or feature requests that are relevant to this UI change.

**Comment by RaviP9973** [comment]
please assign this assign this issue to me @Vignesh025

**Comment by Vignesh025** [comment]
Hey @RaviP9973 , you can proceed!

**Comment by RaviP9973** [comment]
i am sorry i can't work on this 
you can assign it to any other contributer or you close this issue

**Comment by Vignesh025** [comment]
Okay, thanks for letting me know!
