### ISSUE TITLE
[UI] Improve the card ui of campground page

### ISSUE THREAD

**Issue by roushan-code** [VigneshDevHub/CampX#349]
**Description**
Change the card color to improve the visual appearance of card

**Proposed Behavior**

**Screenshots**
![card-design](https://github.com/user-attachments/assets/6ffbad80-71a2-4a41-9358-c2ee9ee938a6)

**Impact**
This will improve the visual appearance of Campgrounds page card

**Comment by Vignesh025** [comment]
Hey @roushan-code , someone is already working on this issue. Feel free to explore the project and raise any new issues!
