### ISSUE TITLE
[FEATURE] Login using google account

### ISSUE THREAD

**Issue by Alienimnida** [VigneshDevHub/CampX#35]
Hello I saw that while registering it is asking for username, email and password but can I use firebase so that users can simply register using their google account? I think it will make the registration process more seamless.

**Comment by Sowmiyajayakumar** [comment]
Hey @Alienimnida ,

Thank you for the suggestion and for taking the time to share your thoughts! I understand the appeal of using Firebase for seamless Google account registration, and it could indeed simplify the process for some users.

However, for this project, I’ve decided to stick with the current registration flow . This aligns better with the overall goals and constraints of the project right now. That said, I’m always open to improvements in the future, and if this becomes a priority, I may revisit the idea.

I appreciate your understanding, and thanks again for your input!

**Comment by Alienimnida** [comment]
Thank you for your reply actually I was exploring the project. Very beautiful UI ngl❤️

**Comment by Vignesh025** [comment]
@Alienimnida , Thank you so much! I'm glad you liked the UI. Feel free to explore more and let me know if you have any suggestions or ideas for improvement. 😊

**Comment by satyamohlan** [comment]
Hi @Vignesh025  I believe that I can integrate google auth using passport in this project. It would be great if you could assign me the issue for the same

**Comment by Vignesh025** [comment]
Hi @satyamohlan ! Could you please create a new issue and provide a detailed explanation of how you plan to integrate Google authentication using Passport.js? This will help us understand your approach better before proceeding.

Thank you!
