### ISSUE TITLE
Images is not visible

### ISSUE THREAD

**Issue by Aman-G-upta** [VigneshDevHub/CampX#350]
![image](https://github.com/user-attachments/assets/0e927634-e827-4e9e-bbd3-63f2021ff4e5)
Please assign me under this issue @Vignesh025

**Comment by Vignesh025** [comment]
what are you going to implement?

**Comment by Aman-G-upta** [comment]
I will implement a fix to ensure proper display of the images.

**Comment by Vignesh025** [comment]
The images are displaying fine on our end. In your screenshot, the images aren’t visible because the user hasn’t uploaded any images when creating the campground.
