### ISSUE TITLE
[FEATURE] : Implementing OTP based forgot password route (Backend + frontend)

### ISSUE THREAD

**Issue by Sourabh782** [VigneshDevHub/CampX#351]
**Is your feature request related to a problem? Please describe.**
it allows users to reset their password if they forgot it, enabling them to login to their account

**Describe the solution you'd like**
I wanted to add backend and frontend of the functionality so that users can reclaim their account even if they forgot their password

Workflow: 
1. user enters their registered email
2. and otp is sent to their email
3. user verifies that otp
4. user reset Their password

![image](https://github.com/user-attachments/assets/ba31a6f3-1c82-4d9d-b000-c4124f8a6131)

**Comment by Vignesh025** [comment]
@Sourabh782 , you can proceed!

**Comment by Vignesh025** [comment]
Hey, just checking in—are you still working on this issue?

**Comment by Sourabh782** [comment]
> Hey, just checking in—are you still working on this issue?

Yess working on that only will soon raise the pr

**Comment by Sourabh782** [comment]
> Hey, just checking in—are you still working on this issue?

Btw if you don't have any problem can you share mapbox_token?

**Comment by Vignesh025** [comment]
@Sourabh782 Since you're not working with the map, you can comment out the map-related parts in the code while working on the feature. Before making the PR, just uncomment those parts, and then submit it.

**Comment by Sourabh782** [comment]
> @Sourabh782 Since you're not working with the map, you can comment out the map-related parts in the code while working on the feature. Before making the PR, just uncomment those parts, and then submit it.

Ohkiee
