### ISSUE TITLE
Github actions for more connectivity!

### ISSUE THREAD

**Issue by smog-root** [VigneshDevHub/CampX#352]
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @Vignesh025 

_**i'm expecting a level with gssoc-ext and hacktoberfest-accepted label**_

**Comment by Vignesh025** [comment]
Hey @smog-root , someone is already working on this issue. Feel free to explore the project and raise any new issues!
