### ISSUE TITLE
Feat: Add a loader

### ISSUE THREAD

**Issue by souvikpramanikgit** [VigneshDevHub/CampX#357]
### Describe the feature

I want to add a loader when you open the website first time

### Add ScreenShots

I want to add a loader when you open the website first time, it can increase the user experience.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vignesh025** [comment]
@souvikpramanikgit , you can proceed!

**Comment by Vignesh025** [comment]
Hey, just checking in—are you still working on this issue?

**Comment by souvikpramanikgit** [comment]
Yeah, i will create a pull request in a hour

**Comment by souvikpramanikgit** [comment]
As i didn't notice properly that this repo is written only in js,ejs, so i can't do this, because i don't know ejs

**Comment by Vignesh025** [comment]
Sure, No problem.
