### ISSUE TITLE
[Doc]:  Adding a Project Structure Map

### ISSUE THREAD

**Issue by siri-chandana-macha** [VigneshDevHub/CampX#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Adding a clear structure map in the documentation to guide contributors on where specific files and folders are located and what they contain.

### Suggested Change

**For example:**

Project Root
├── src/ &nbsp;&nbsp;&nbsp;&nbsp;              # Core application files
│ ├── components/ &nbsp;&nbsp;&nbsp;&nbsp;                         # Reusable UI components
│ ├── services/ &nbsp;&nbsp;&nbsp;&nbsp;                                # API calls and business logic
│ ├── utils/ &nbsp;&nbsp;&nbsp;&nbsp;                                     # Utility functions
│ └── index.js  &nbsp;&nbsp;&nbsp;&nbsp;                               # Main entry file
├── assets/ &nbsp;&nbsp;&nbsp;&nbsp;                                   # Images, icons, and other static assets
├── config/    &nbsp;&nbsp;&nbsp;&nbsp;                                 # Configuration files (e.g., env variables)
└── README.md   &nbsp;&nbsp;&nbsp;&nbsp;                          # Project overview and instructions

### Rationale

This helps new contributors quickly understand the project layout and find files easily.

### Urgency

Medium

### Acknowledgements

- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/CampX/blob/dev/CONTRIBUTING.md)*
- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I have starred the repository
- [X] I am willing to work on this issue (optional)

**Comment by Vignesh025** [comment]
Hey @siri-chandana-macha ,The project structure is already outlined in the contributing.md file, but some comments are incorrect. Could you review and correct them instead?

**Comment by siri-chandana-macha** [comment]
Yeah sure

**Comment by siri-chandana-macha** [comment]
please assign me

**Comment by Vignesh025** [comment]
You can proceed!
