### ISSUE TITLE
Improve campground.js Schema with Validation, Timestamps, and Error Logging

### ISSUE THREAD

**Issue by smog-root** [VigneshDevHub/CampX#361]
**Suggested Enhancements:**

**1. Add Validation Constraints:**

- Ensure title has a minimum length to avoid short or empty titles (e.g., { minlength: 3 }).
- Ensure price is positive to prevent incorrect values (e.g., { min: 0 }).

**2. Include Timestamps:**

- Add { timestamps: true } to the CampgroundSchema to track when a campground was created or last updated.

**3. Enhance Error Logging:**

- Improve error handling in the findOneAndDelete middleware by adding more detailed logs or notifications for better debugging.

**Benefits:**

- Enhanced data validation and integrity.
- Improved tracking of campground updates and additions.
- Better error insights for debugging.

_**I'm expecting a gssoc-ext with level labels!**_ @Vignesh025

**Comment by kuhupatel15** [comment]
I can work on this by implementing error handling using try catch and conditions on attributes of campground model. Please  assign it to me. @Vignesh025

**Comment by smog-root** [comment]
> I can work on this by implementing error handling using try catch and conditions on attributes of campground model. Please  assign it to me. @Vignesh025 

I have already raised the issue!!

You can create your own issue and work on it!! @kuhupatel15

**Comment by Vignesh025** [comment]
@smog-root , you can proceed!
