### ISSUE TITLE
 Feat: Weather integration to show weather of each campgrounds location.

### ISSUE THREAD

**Issue by Jordian0** [VigneshDevHub/CampX#362]
### Describe the feature

 Incorporate a weather API to show current and forecasted weather conditions for each campground location.

### Add ScreenShots

Having weather information directly integrated into the campground details eliminates the need for users to check multiple websites,

![image](https://github.com/user-attachments/assets/231de5f4-fdc0-49cd-93e8-6fe5ccbc206c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vignesh025** [comment]
Hey @Jordian0 , We don't need this feature right now, but thanks for the suggestion
