### ISSUE TITLE
Feat:add rate limiter to login api 

### ISSUE THREAD

**Issue by AyushSharma72** [VigneshDevHub/CampX#364]
### Describe the feature

i want to add a rate limiter to the login api 
advantages:
prevent bots brute force attack
enhance security
reduce load on api

### Add ScreenShots

please assign this issue to me @Vignesh025 
![image](https://github.com/user-attachments/assets/285adc3d-a2d2-4eac-8c35-4117b5cc2a7d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vignesh025** [comment]
@AyushSharma72 , you can proceed!
