### ISSUE TITLE
Feat: add scroll bar to the comments section

### ISSUE THREAD

**Issue by AyushSharma72** [VigneshDevHub/CampX#365]
### Describe the feature

if there are a lot of comments then the page will become very large 
and it will not look good i want to add  the comments inside container which is fixed and can be scrolled

### Add ScreenShots

![image](https://github.com/user-attachments/assets/8a8ae84d-f74e-4ad5-83d2-f30cb3a8805d)

please assign this issue to me @vi

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vignesh025** [comment]
@AyushSharma72 , you can proceed!
