### ISSUE TITLE
Feat:add loader when creating a new campground

### ISSUE THREAD

**Issue by AyushSharma72** [VigneshDevHub/CampX#366]
### Describe the feature

when the add campground button is clicked there is no loader while the website is processing the data 

i want to add a loader when the data is processed 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/e48978d7-aee7-44c7-b0ba-63c3e5f0696c)

please assign this issue to me @vi

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vignesh025** [comment]
@AyushSharma72 , you can proceed!
