### ISSUE TITLE
Feat:Add About Page

### ISSUE THREAD

**Issue by NK-Works** [VigneshDevHub/CampX#368]
### Describe the feature

A comprehensive about page of the website

### Add ScreenShots

Currently there is no about page I can add it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vignesh025** [comment]
@NK-Works , We don't need this feature right now, but thanks for the suggestion
