### ISSUE TITLE
Feat: Add Contributors page

### ISSUE THREAD

**Issue by NK-Works** [VigneshDevHub/CampX#369]
### Describe the feature

Add a contributors page for the website

### Add ScreenShots

No contributors page available currently

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vignesh025** [comment]
@NK-Works , We don't need this feature right now, but thanks for the suggestion
