### ISSUE TITLE
Feat:Add Contact Us Page

### ISSUE THREAD

**Issue by NK-Works** [VigneshDevHub/CampX#371]
### Describe the feature

No contact us page available for the website 

### Add ScreenShots

I can add a contact us page for the website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vignesh025** [comment]
@NK-Works , We don't need this feature right now, but thanks for the suggestion
