### ISSUE TITLE
Feat:Confirm password and Button of sign up to Google 

### ISSUE THREAD

**Issue by Aditya90456** [VigneshDevHub/CampX#372]
### Describe the feature

Confirm password and Button of sign up to Google 

### Add ScreenShots

![Campgrounds and 6 more pages - Personal 2 - Microsoft​ Edge Beta 11_4_2024 9_27_15 PM](https://github.com/user-attachments/assets/a0891328-3fcb-4c1e-9485-930c26533e1d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vignesh025** [comment]
@Aditya90456 , just proceed with confirm password.

The signup with google feature is not required.

**Comment by Aditya90456** [comment]
please level 2 @Vignesh025

**Comment by Vignesh025** [comment]
It's a minor feature, so only level 1 can be given.
Why did you close this issue?

**Comment by Aditya90456** [comment]
website is not opening @Vignesh025

**Comment by Vignesh025** [comment]
@Aditya90456 , https://campx-1.onrender.com/ is this the link you're using?
