### ISSUE TITLE
[Custom]: <Add Loading Indicator and Smooth Transition for Register, Login, and Logout Processes>

### ISSUE THREAD

**Issue by devashish2006** [VigneshDevHub/CampX#374]
### Issue Summary

Currently, the application does not provide any visual feedback during the signup, login, or logout processes, which can lead to a delayed or inconsistent user experience. Implementing a loading indicator and smooth transitions during these actions would enhance the UX by giving users a clearer sense of progress and improving responsiveness.

### Issue Description

Currently, the application does not provide any visual feedback during the signup, login, or logout processes, which can lead to a delayed or inconsistent user experience. Implementing a loading indicator and smooth transitions during these actions would enhance the UX by giving users a clearer sense of progress and improving responsiveness.

### Priority

High - Requires urgent attention

### Category

- [X] Enhancement
- [ ] Refactor
- [ ] Security
- [X] Design
- [ ] Other

**Comment by Vignesh025** [comment]
Hey @devashish2006 , someone is already working on this issue. Feel free to explore the project and raise any new issues!
