### ISSUE TITLE
Feat: Adding proper "About Us" Page with Comprehensive Content & Design Enhancements

### ISSUE THREAD

**Issue by dipexplorer** [VigneshDevHub/CampX#376]
### Describe the feature

The current "About Us" section lacks comprehensive content, making it challenging for users to understand our platform's purpose, values, and unique offerings.

### Add ScreenShots
![Screenshot (270)](https://github.com/user-attachments/assets/052214b9-0d47-4099-aec3-5a7616d2d889)

Expected Outcome:
A redesigned "About Us" page with detailed, compelling content that reflects the purpose and value of CampX.
Visuals and/or interactive elements that make the page more engaging.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vignesh025** [comment]
Hey @dipexplorer,We don't need this feature right now, but thanks for the suggestion.
