### ISSUE TITLE
[BUG] Add Proper Icons for Login and Logout; Ensure Logout Option Visibility

### ISSUE THREAD

**Issue by dipexplorer** [VigneshDevHub/CampX#377]
### Description

Currently, there are no icons associated with the login and logout buttons, which impacts user experience and makes navigation less intuitive. Additionally, the logout option is not consistently visible across different pages and screen sizes, potentially leading to confusion for users trying to log out.

### Screenshots

![05 11 2024_13 50 35_REC](https://github.com/user-attachments/assets/fcdc5931-582c-4f30-8045-f1c436af0291)

![05 11 2024_13 49 21_REC](https://github.com/user-attachments/assets/cdf168ed-cadb-4017-b96a-ad2830adb9bf)

### Any additional information?

Expected Outcome:

Add intuitive and theme-aligned icons next to the login and logout options.
Ensure the logout option is consistently visible on all screen sizes and accessible from all relevant pages, improving the overall navigation and usability of the site.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/CampX/blob/dev/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Vignesh025** [comment]
@dipexplorer , We don't need this feature right now, but thanks for the suggestion
