### ISSUE TITLE
Feat Adding proper Comprehensive "Terms and Conditions" Page

### ISSUE THREAD

**Issue by dipexplorer** [VigneshDevHub/CampX#378]
### Describe the feature

The website currently lacks a dedicated "Terms and Conditions" page, which is essential for establishing clear guidelines and policies for users. This page should cover key aspects such as user responsibilities, data usage, limitations of liability, and intellectual property rights, ensuring both user awareness and legal compliance.

### Add ScreenShots

![Screenshot (270)](https://github.com/user-attachments/assets/8665e168-730c-4900-88f2-14526076c7ee)

Expected Outcome:

A well-structured "Terms and Conditions" page that covers all necessary legal and usage terms relevant to the website.
Clear, user-friendly language that enhances transparency and builds user trust.
A link to the "Terms and Conditions" page added to the footer for easy accessibility.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vignesh025** [comment]
@dipexplorer , We don't need this feature right now, but thanks for the suggestion.
