### ISSUE TITLE
Feat: Adding a Comprehensive Footer with Social Media Links, Contact Details, and Brand Information

### ISSUE THREAD

**Issue by dipexplorer** [VigneshDevHub/CampX#379]
### Describe the feature

The website currently lacks a detailed footer section, which affects the overall professional look and limits user engagement options. A proper footer should be added that includes social media icons for easy navigation to our social platforms, contact details for user support, and brand information (brand name and tagline) to reinforce our identity.

### Add ScreenShots

![Screenshot (270)](https://github.com/user-attachments/assets/581184a3-8c89-4d19-9e93-ec1fdf2d30ed)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vignesh025** [comment]
@dipexplorer, We don't need this feature right now, but thanks for the suggestion.
