### ISSUE TITLE
Feat: Develop a Comprehensive and User-Friendly FAQ Section

### ISSUE THREAD

**Issue by dipexplorer** [VigneshDevHub/CampX#380]
### Describe the feature

The current website lacks a dedicated FAQ (Frequently Asked Questions) section, which is essential for addressing common user queries and improving the overall user experience. 

### Add ScreenShots

![Screenshot (270)](https://github.com/user-attachments/assets/9d0fbc75-f691-40d0-ab9b-92a3a5d21c39)

Expected Outcome:

A structured FAQ section organized into categories (e.g., Account, Services, Payment, etc.) for ease of navigation.
Clear, informative answers to common questions, ensuring users can resolve issues independently.
Mobile-friendly design with collapsible or accordion-style questions to keep the layout clean and readable on all devices.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vignesh025** [comment]
@dipexplorer, We don't need this feature right now, but thanks for the suggestion.
