### ISSUE TITLE
Feat:  Set limit for review comment part  Frontend + Backend. 

### ISSUE THREAD

**Issue by Suvadip-sana** [VigneshDevHub/CampX#383]
### Describe the feature

As you can see in the attached video there is no check to protect the large input of review comment part. User can give large review comment as large as possible if they want. Which is not good practice. And also there is no need that much long reviewa for one campsite.

- So here I would like to introduce a good features that, If one review comment length exceed 150 then it show a `Read more` anchor tag. After clicking on it, It open a Scrollable model in the middle of he screen to display full length review. Which is also responsive for all screen. Just like this Video.

https://github.com/user-attachments/assets/9a36f9cf-dfda-4e39-9238-ea85c18f25d5

- And also I add a proper backend logic to prevent the large review comment input in `create review` route. I set the limit of 600 character, I think this is enough for a review comment.   If this limit exceed then it display a error flash message. And redirect to `show list` route, means that new review added form.

### Add ScreenShots

https://github.com/user-attachments/assets/a3e5bf0c-99f0-432d-afc7-84f825d61c8b

@Vignesh025   Assign it to me. I think it's that major issue which need attention.  Assign it under `label-3` because both frontend and backend implementations are there. I think this is fair.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vignesh025** [comment]
@Suvadip-sana , you can proceed!

**Comment by Suvadip-sana** [comment]
@Vignesh025 
`label-1`
It's supposed to be `label-2` atleast?

**Comment by Suvadip-sana** [comment]
@Vignesh025 
Ok got it.
