### ISSUE TITLE
[BUG] Index page changes is no reflect.

### ISSUE THREAD

**Issue by Suvadip-sana** [VigneshDevHub/CampX#400]
### Description

My PR #395 

For feature increment of index page is not reflect. Is this is an ISSUE. Then assign it me.

### Screenshots

![image](https://github.com/user-attachments/assets/280af065-88b4-429c-a2be-17776194ac19)

@Vignesh025 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/CampX/blob/dev/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Vignesh025** [comment]
@Suvadip-sana  It's not an issue. 
I removed that line.
we are okay with displaying a title of up to 70 characters length.
