### ISSUE TITLE
[FEATURE] so there is no back button when we are seeing any campground photos and details. This is bad User experience

### ISSUE THREAD

**Issue by VinayLodhi1712** [VigneshDevHub/CampX#43]
**Is your feature request related to a problem? Please describe.**
User always frustrated when there is no back button on some pages and on that page where any user seeing any campgrounds photos and details they are frustated and need to go to home page again.

**Describe the solution you'd like**
By creating a back button which will take user to where he was previously and I think in your project mant places back button is needed.

**Describe alternatives you've considered**
alternatives is that go to home page by clicking logo which is bad user experience

**Additional context**
![campground](https://github.com/user-attachments/assets/ea9efb26-b973-4c66-9fdd-e9c29dbbf9ee)

See no back button here.

Also, plz assign me this issue under gssoc extended level and hactoberfest level so it will help me also.

**Comment by Vignesh025** [comment]
Hey @VinayLodhi1712 ,

Yeah, sure! That's a great observation. I’m assigning this issue to you so you can work on adding the back button to improve navigation. Once you’ve finished implementing it, please share a screenshot here so I can review it and suggest any necessary changes. Thanks for taking this on!

**Comment by VinayLodhi1712** [comment]
ok thanks for assigning i am now started working.

**Comment by Vignesh025** [comment]
@VinayLodhi1712 ,You're welcome! Please note that you should generate your own tokens for the .env file, such as Mapbox and Cloudinary API keys.

**Comment by VinayLodhi1712** [comment]
mapbox is asking bank details and all that is the problem so can you share map access token.

**Comment by Vignesh025** [comment]
@VinayLodhi1712 , Do you have any college mail id?
 If you do , you can sign up using that and it wont ask for any bank details.

**Comment by VinayLodhi1712** [comment]
No our college does not provide any mail id. I want to work on your awesome project but i think if that problem happen then i will not able to work . If you have any other idea so that i can run your project without this then tell me.

**Comment by Vignesh025** [comment]
Reach out to me on Discord, and I'll guide you on what to do!
