### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by shivamy009** [VigneshDevHub/CampX#45]
![Screenshot 2024-10-02 021200](https://github.com/user-attachments/assets/9e071480-c8cb-4065-a153-db4e0a20fefc)
 add feature here if user is not register and visa versa

**Comment by Vignesh025** [comment]
Hey @shivamy009 ,

Could you please elaborate on what exactly you want to implement regarding user registration? It would be great if you could also share some examples or screenshots of how this feature will work, so I can better understand your approach.

Looking forward to your clarification!

**Comment by shivamy009** [comment]
> Hey @shivamy009 ,
> 
> Could you please elaborate on what exactly you want to implement regarding user registration? It would be great if you could also share some examples or screenshots of how this feature will work, so I can better understand your approach.
> 
> Looking forward to your clarification!

Add feature if "user already registered" in signup page and add feature if "user don't have account"

**Comment by Vignesh025** [comment]
It seems like you're asking for a feature that may already exist, as the app currently notifies users if they are not registered when attempting to log in and if a registered user tries to sign up again. Could you clarify what additional feature you're proposing? I'd appreciate more details so I can understand your request better.

**Comment by shivamy009** [comment]
> It seems like you're asking for a feature that may already exist, as the app currently notifies users if they are not registered when attempting to log in and if a registered user tries to sign up again. Could you clarify what additional feature you're proposing? I'd appreciate more details so I can understand your request better.

![Screenshot 2024-10-02 213812](https://github.com/user-attachments/assets/bb725a4a-10d7-4194-9578-ea9e6505a4c2)
i want to add this feature if user have already account and visa versa

**Comment by Vignesh025** [comment]
Sure, go ahead and proceed with it! I'm assigning this feature to you. Looking forward to your implementation!

**Comment by Vignesh025** [comment]
do you want this to be part of hacktoberfest?

**Comment by shivamy009** [comment]
> do you want this to be part of hacktoberfest?

gssocextd

**Comment by Vignesh025** [comment]
Hey @shivamy009 , are you still working on this issue? If not, please let me know so I can assign it to someone else. Thanks!

**Comment by roushan-code** [comment]
Hi @Vignesh025 , Can you assign it to me? I want to work on this feature.

**Comment by Sauhard74** [comment]
@Vignesh025 i can work on this ! can you assign it to me if no one is working on it

**Comment by Vignesh025** [comment]
@roushan-code , you can proceed!
