### ISSUE TITLE
[FEATURE] Automated Greeting Workflow

### ISSUE THREAD

**Issue by samyak-aditya** [VigneshDevHub/CampX#46]
**Is your feature request related to a problem? Please describe.**

I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Additional context**
Hey @Vignesh025 please assign me this task with labels "gssoc-ext" and "level1"

**Comment by Vignesh025** [comment]
Sure @samyak-aditya , you can proceed! I'm assigning this task to you.

**Comment by Vignesh025** [comment]
*Thank you for Contributing!*
