### ISSUE TITLE
[FEATURE] Add a Admin Feature

### ISSUE THREAD

**Issue by Vignesh025** [VigneshDevHub/CampX#5]
Problem:
The admin needs to login to the database to delete the spam campgrounds.

Solution:
A feature for the project admin to delete or edit any campground.

Alternatives:
Any other alternatives are also welcomed.

*If you're going to work on this issue, create a new issue explaining your changes and mention this issue.*

**Comment by ARRY7686** [comment]
Hi @Vignesh025 I found your issue really interesting and would really like to contribute to it can you pls assign it to me

**Comment by Vignesh025** [comment]
Hi @ARRY7686 ,

Thank you for your interest in contributing! I appreciate your enthusiasm. However, someone is already currently working on this issue.

I encourage you to check out other open issues in the repository, or feel free to suggest any ideas for new features or improvements.

Looking forward to your contributions!

**Comment by Alienimnida** [comment]
Hello can I take this up if it is not assigned to anyone rn?

**Comment by ARRY7686** [comment]
It is assigned
to me
will make the PR by tomorrow

**Comment by Vignesh025** [comment]
You can reply with:

Hi @Alienimnida ,

Thanks for your interest! This issue is already being worked on by someone else. However, we’d love to hear any other ideas you have or contributions you'd like to make. Feel free to check out other open issues or suggest new ones!

Looking forward to your contributions!

**Comment by Vignesh025** [comment]
Hi @ARRY7686 ,

As I mentioned earlier, this issue has already been assigned to someone else. Feel free to explore other issues or suggest new ideas. We’d love to see your contributions!
