### ISSUE TITLE
Improvement of the footer

### ISSUE THREAD

**Issue by Sneharaj7645653** [VigneshDevHub/CampX#50]
**Description**
The current footer is quite minimalistic and could benefit from enhancements to give the website a more professional appearance.

**Current Behavior**
Currently, the footer only has the year mentioned.

**Proposed Behavior**
After making the necessary changes, the footer will contain sections like: "About Us", links to social media handles, etc.

**Screenshots**
The following image is of a footer. A similar kind of layout will be suitable for the CampX website as well.
![image](https://github.com/user-attachments/assets/c98c3dc0-d8e5-4a4d-9bbc-699734740d54)

**Impact**
It will help to improve the visual appeal of the website.

**Comment by Vignesh025** [comment]
Sure @Sneharaj7645653 , you can proceed with this. I'm assigning it to you. If you need any specific links for the social media handles or other sections, feel free to reach out, and I'll provide them!

**Comment by Sneharaj7645653** [comment]
Alright.

**Comment by Vignesh025** [comment]
Hey @Sneharaj7645653 , are you still working on this issue? If not, please let me know so I can assign it to someone else. Thanks!

**Comment by Sneharaj7645653** [comment]
Currently, I am working on the footer. You may assign it to someone else.

**Comment by Vignesh025** [comment]
Hey @Sneharaj7645653 , if you're working on the footer, shall I assign the home UI task to someone else?

**Comment by Sneharaj7645653** [comment]
Yes
