### ISSUE TITLE
[UI] Enhance Navbar for Improved UX and Accessibility

### ISSUE THREAD

**Issue by RanitDERIA** [VigneshDevHub/CampX#52]
**Description**

The current navbar in the CampX web application is functional but could be improved to provide a better user experience and enhanced accessibility. I propose the following improvements:

*1. Responsive Design Enhancements:* Ensure the navbar adapts seamlessly across all screen sizes, including mobile and tablet views.
*2. Improved Navigation Links:* Add hover effects and improve the link arrangement for better clarity and usability.
*3. Accessibility Updates:* Implement ARIA roles and attributes to make the navbar more accessible to users with disabilities.
*4. Dropdown Menus:* Introduce dropdown menus for better organization of content.

These enhancements will provide a more user-friendly and polished interface for CampX, aligning with the community-driven nature of the platform.

**Please include Labels:**

- gssoc-ext
- hacktoberfest-accepted
- level: beginner (or level: intermediate based on your skill level)

**Assignee Request:**
I would like to be assigned to this issue as part of **GSSoC'24**. I have experience working with front-end technologies like HTML, CSS, Bootstrap, and JavaScript, and I’m confident I can implement these enhancements efficiently. Please assign this issue to me so I can get started.

Looking forward to your response!

**Comment by Vignesh025** [comment]
Sure @RanitDERIA , You can proceed. I'm assigning this to you!

**Comment by rinkitadhana** [comment]
can i work on this issue?

**Comment by Vignesh025** [comment]
Hey @rinkitadhana , I'm sorry, but @RanitDERIA  is already working on this issue. Feel free to explore the project and create new issues if you find something else to work on!

**Comment by RanitDERIA** [comment]
**Thank you**, @Vignesh025, for merging my PR! It was a great experience contributing to the project and collaborating with you. I appreciate your feedback and guidance throughout the process. Looking forward to more opportunities to contribute! 😊
