### ISSUE TITLE
[FEATURE] Dark mode toggle

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [VigneshDevHub/CampX#54]
**Is your feature request related to a problem? Please describe.**
there is not preferences in the website to toggle between dark and light mode.

**Describe the solution you'd like**
I will create a toggle in the navabar which will allow the user to toggle between dark mode and light mode.

**Comment by Vignesh025** [comment]
Thank you for the suggestion! However, we’re currently designing our UI to be neutral, without a specific dark or light theme. So, at this stage, we don’t feel it’s necessary to add a toggle feature. We appreciate your understanding!
