### ISSUE TITLE
[FEATURE]  review section gssoc extd

### ISSUE THREAD

**Issue by taansssss** [VigneshDevHub/CampX#55]
Currently, CampX lacks a review feature, which makes it difficult for users to share their experiences or read feedback about campgrounds. Without this, users cannot make fully informed decisions about where to camp or contribute to the platform by providing helpful information about the campgrounds they’ve visited.

A review functionality where users can leave both star ratings (e.g., 1-5 stars) and written reviews for each campground. Reviews should be tied to user profiles and display the submission date. This feature would allow users to share key details like amenities, conditions, and overall experiences, making the platform more engaging and informative.

1. A simple thumbs-up/thumbs-down system, but it lacks depth.  
2. Integrating third-party review platforms like Google Reviews, though it would require users to leave CampX.  
3. Star ratings without written reviews, but that would not offer enough detailed feedback.

Adding a review system would encourage user engagement and make the platform more useful for the community, allowing users to better assess campgrounds and contribute valuable insights

**Comment by Vignesh025** [comment]
Thank you for the suggestion! However, the review feature you mentioned is already available on the website. Please feel free to check it out. Let me know if you have any other ideas or questions. Thank you!
