### ISSUE TITLE
[FEATURE] Google Authentication with Passport.js

### ISSUE THREAD

**Issue by ARRY7686** [VigneshDevHub/CampX#56]
### Description
 We propose integrating Google authentication into the project using Passport.js to provide users with a seamless login option using their Google accounts. This would enhance user experience by reducing the manual steps in the registration process, making it faster and more convenient.

**Why Passport.js?**

Passport.js is a popular and flexible authentication middleware for Node.js that allows us to implement various authentication strategies, including OAuth2.0 for Google.
Using Passport-Google-OAuth20, we can securely authenticate users through Google and streamline the process without storing or managing sensitive user data like passwords.

### Plan of Action:

**Install Dependencies:**

Add passport and passport-google-oauth20 to the project.
Setup Google Credentials:

Create credentials from the Google Developer Console to get a Client ID and Client Secret.
Configure redirect URIs to handle Google login responses.
Modify the Authentication Flow:

Implement a new login route to handle Google login using Passport.js.
Modify the backend to authenticate users and create new user profiles upon successful login with Google.
UI Changes:

Add a "Login with Google" button on the registration page that redirects users to Google's OAuth page for authentication.
Testing:

Ensure the authentication process works end-to-end, including Google login, redirect handling, and storing user data

**Benefits:**

Provides a quicker and simpler login process for users.
Increases user security by offloading authentication management to Google.
Reduces the need for manual registration.

**Comment by ARRY7686** [comment]
Can you pls Assign this issue to me and add label it as Hacktober Fest

**Comment by Vignesh025** [comment]
Thank you for the detailed proposal! However, we want to keep the authentication process basic for now and won't be implementing this feature at the moment. We appreciate your suggestion though! Thank you.
