### ISSUE TITLE
[BUG] Changing the User Model 

### ISSUE THREAD

**Issue by MOHINI1403** [VigneshDevHub/CampX#57]
**Describe the bug**
The role field into the user model should not be string it should be enum otherwise it would be very difficult to filter out because multiple users will be writing different values as role and spelling.

**To Reproduce**
Go to models folder check for user.js file within that check for role you will find the issue. 

**Expected behavior**
After this when we have created the enum the user can only select among the specific options.

Please assign this issue to me so that i could work on this and resolve the bug.

**Comment by Vignesh025** [comment]
That’s a great idea! Please proceed, I’m assigning this issue to you. Thank you for taking the initiative.

**Comment by preranah7** [comment]
Hey @Vignesh025 @MOHINI1403 , I would like to give a suggestion that if we allow users to select their roles any one of the spam user can edit or delete the listings and reviews if they have their role as admin. Users not knowing their roles would be the safer side to consider. Kindly consider this point and fix the bug.
Thankyou.

**Comment by Vignesh025** [comment]
Hey @preranah7 , Thank you for your suggestion! Yes, we’re not allowing users to select their roles themselves. The current task is just converting the role field from a string to an enum. Since we’ve hardcoded the role "admin" in various places, it’s a best practice to switch to an enum for better consistency. Thanks again!

**Comment by MOHINI1403** [comment]
> That’s a great idea! Please proceed, I’m assigning this issue to you. Thank you for taking the initiative.

Thank you for assigning the issue I will fix this bug.

**Comment by latpategaurav** [comment]
hey @Vignesh025 i tried solving the issue and have reaised a pr
kindly checkout the pr

**Comment by MOHINI1403** [comment]
Hello @Vignesh025 I have fixed the bug and raise the PR into the test branch as it was assigned to me . Please check it out if you think there are certain additional changes which need to be done . Please let me know.

**Comment by Vignesh025** [comment]
Hey @MOHINI1403 , are you still working on this issue? If not, please let me know so I can assign it to someone else. Thanks!

**Comment by preranah7** [comment]
May I do it if anyone is not doing?

**Comment by Vignesh025** [comment]
@preranah7 , I'll let you know.

**Comment by preranah7** [comment]
Sure.

**Comment by Vignesh025** [comment]
Hey @preranah7 , You can proceed with working on this issue. I'm assigning this to you!

**Comment by preranah7** [comment]
Sure @Vignesh02.

**Comment by raj-adi00** [comment]
There has been no activitty. @Vignesh025 can you assign it to me

**Comment by Vignesh025** [comment]
@raj-adi00 , Thank you for the interest but we are working on it.
