### ISSUE TITLE
[UI] UI and Styling Improvements Needed for Campgrounds Page

### ISSUE THREAD

**Issue by rinkitadhana** [VigneshDevHub/CampX#59]
**Description**
The current design of the campgrounds page is quite basic. The card elements lack visual appeal and need enhancement. Additionally, the buttons are blue, which does not align with the overall color scheme of the UI.

**Current Behavior**
The current design of the campgrounds page needs improvement. Specifically:

Cards: The cards should be redesigned with better padding and an updated color scheme to enhance the visual appeal.
Headers: The headers within the cards need to be styled to be more prominent and consistent with the rest of the UI.
Buttons: The buttons are currently blue, which doesn't match the color scheme of the overall design. These should be updated to follow the established color pattern for a cohesive look.

**Proposed Behavior**
After the changes, the campgrounds page will have a more polished look. The cards will feature a zinc-colored background, with improved padding and margins for better spacing. Buttons will follow the same color scheme as the cards for a consistent design. The headers within the cards will be more prominent, creating a cleaner and more cohesive UI overall.

**Screenshots**
![Screenshot 2024-10-03 233303](https://github.com/user-attachments/assets/9ff9d98e-4a18-4456-a44a-fc16c7d8ad22)

also this issue is for hacktoberfest, so add the label

can you assign this to me ?

**Comment by Vignesh025** [comment]
Your screenshot hasn't been uploaded. can you upload it again?

**Comment by rinkitadhana** [comment]
Done, and please assign this to me

**Comment by Vignesh025** [comment]
Someone else is currently working on this as well. I'll discuss with them and let you know. Thanks for your interest!

**Comment by rinkitadhana** [comment]
okay, I'm waiting

**Comment by Vignesh025** [comment]
@rinkitadhana You're good to go! I'm assigning you this issue. Feel free to proceed.

**Comment by rinkitadhana** [comment]
also can i use tailwind in this project? if you guys aren't using it.

**Comment by Vignesh025** [comment]
Yes, feel free to use Tailwind in the project!

**Comment by Vignesh025** [comment]
Hey @rinkitadhana , are you working on this issue? If not, please let me know so I can assign it to someone else. Thanks!

**Comment by rinkitadhana** [comment]
yes I'm currently working on this, please don't assign this to someone else, also can i use tailwind in it?

**Comment by Vignesh025** [comment]
Yes @rinkitadhana , You can use tailwind.

**Comment by rinkitadhana** [comment]
okay I'm working on it

**Comment by Vignesh025** [comment]
One suggestion from my side is to have some hover effects on the cards.

**Comment by rinkitadhana** [comment]
yeah i was thinking about that, but on buttons or cards?

**Comment by Vignesh025** [comment]
on cards.
if you think it looks well on buttons,
you can do both.

**Comment by rinkitadhana** [comment]
lets see

**Comment by rinkitadhana** [comment]
hey can you provide me the  mapbox token, i dont have a mapbox account and they are asking for creditcard details and i dont have one.

**Comment by Vignesh025** [comment]
Do you have college mail id?

**Comment by rinkitadhana** [comment]
no, just want the mapbox token to locally test my code, it's almost over.
can you give me the token?

**Comment by Vignesh025** [comment]
> no, just want the mapbox token to locally test my code, it's almost over.
> can you give me the token?

reach out to me in discord

**Comment by rinkitadhana** [comment]
okay

**Comment by rinkitadhana** [comment]
I texted you

**Comment by rinkitadhana** [comment]
please check your discord messages.

**Comment by Vignesh025** [comment]
Hey @rinkitadhana  , are you still working on this issue? If not, please let me know so I can assign it to someone else. Thanks!

**Comment by rinkitadhana** [comment]
NO
