### ISSUE TITLE
[UI] Improve Campgrounds UI

### ISSUE THREAD

**Issue by Vignesh025** [VigneshDevHub/CampX#6]
**Description**
Improve the UI of Campgrounds page to be more attractive

**Current Behavior**
The current UI is minimalist.

*If you're going to work on this issue, create a new issue explaining your changes and mention this issue.*

**Comment by BinaryBhakti** [comment]
I want to work on this issue. Please assign this issue to me.

**Comment by Vignesh025** [comment]
Hey @BinaryBhakti , Create a new issue stating all the changes you want to make and mention this issue like (issue #6). I'll review it and assign it to you.
