### ISSUE TITLE
[FEATURE] Automation

### ISSUE THREAD

**Issue by shubhagarwal1** [VigneshDevHub/CampX#64]
1. Automate Labeling of Issues and PRs Based on Keywords
2. Automate GitHub Release Creation with Notes and Tagging
3. GitHub Action for Automatically Displaying All Contributors in README

**Comment by Vignesh025** [comment]
Sure, you can work on those tasks! Just please make sure to create a separate pull request for each GitHub Action to the test branch. This will help keep everything organized and make it easier to review. Thank you!
