### ISSUE TITLE
[FEATURE] Forget password and Reset password

### ISSUE THREAD

**Issue by shiv-sk** [VigneshDevHub/CampX#68]
Implementation of forget password and password reset 
There no forget and password reset functionality is present in the campX 
It is one of the basic functionality that most of the web apps follows.
By implementing it would increase user experience

Implementation 
Model: Probably no changes
Controller: Adding the forget password functionality and password reset functionality
views: Adding button of forget password(login page)

**Comment by ak3264114** [comment]
please assign me the issue under gssoc 24 and hacktoberfest

**Comment by Vignesh025** [comment]
Sure @shiv-sk , you can proceed with the implementation. I'm assigning this issue to you. Looking forward to seeing your work!

**Comment by Vignesh025** [comment]
Hey @shiv-sk , are you still working on this issue? If not, please let me know so I can assign it to someone else. Thanks!

**Comment by ak3264114** [comment]
@Vignesh025 you can assign me this issue if @shiv-sk is not working on it

**Comment by Vignesh025** [comment]
Hey @shiv-sk , I'll let you know!

**Comment by shiv-sk** [comment]
@Vignesh025 bro I am started working on it and started to studying how to implement it

**Comment by Vignesh025** [comment]
Hey @shiv-sk , no worries! I was just making sure everyone is still working on their assigned tasks. Take your time, and feel free to submit the PR when you're ready. Thanks for the update!

**Comment by shiv-sk** [comment]
@Vignesh025 sorry bro for my late reply

**Comment by shiv-sk** [comment]
@ak3264114 bro this is my email shivanandkhudanapur592@gmail.com if u really want to work on this issue please msg me

**Comment by Vignesh025** [comment]
@shiv-sk No worries at all!

**Comment by Vignesh025** [comment]
@ak3264114 , you may proceed with this task, I'm assigning it to you.

**Comment by Vignesh025** [comment]
Hey @ak3264114  , are you still working on this issue? If not, please let me know so I can assign it to someone else. Thanks!
