### ISSUE TITLE
[UI] Improve Home UI

### ISSUE THREAD

**Issue by Vignesh025** [VigneshDevHub/CampX#7]
**Description**
Make the Home Page to be more attractive.

**Current Behavior**
The current UI is minimalistic.

*If you're going to work on this issue, create a new issue explaining your changes and mention this issue.*

**Comment by Sneharaj7645653** [comment]
Hey there Vignesh! I would like to work on this issue. I am familiar with CSS. 
So, could you assign me this problem?

**Comment by Vignesh025** [comment]
Sure, @Sneharaj7645653 ! Create a new issue and mention what you want to improve and mention this issue like #issue_number 
and I'll assign it to you.

**Comment by Sneharaj7645653** [comment]
I've created issue #7. Please review the changes I proposed and proceed accordingly.

**Comment by Vignesh025** [comment]
@Sneharaj7645653 I've assigned it to you, You can proceed.

**Comment by chetanck03** [comment]
Hi , assign this issue to me , I will improving the layout, typography, and adding engaging elements while maintaining a user-friendly interface.

**Comment by Vignesh025** [comment]
@chetanck03 ,Thank you for your interest, but someone else is currently working on the Home Page. Feel free to explore other issues where your skills can contribute!

**Comment by aditi13y** [comment]
Hi there,Please assign this issue to me.
