### ISSUE TITLE
[FEATURE] Add "See Password" Feature with Eye Icon for Login/Register Forms

### ISSUE THREAD

**Issue by devansh-dek** [VigneshDevHub/CampX#72]
Add a "See Password" feature to the login and registration forms, allowing users to toggle password visibility by clicking on an eye icon. This feature will enhance user experience by enabling them to view the password they've typed for better accuracy and convenience.

![(84) Vishal   Shekhar, Shahid Mallya, Nisha Mascarenhas, Marianne D'cruz Aiman - Kukkad - YouTube - Google Chrome 05-10-2024 11_08_39](https://github.com/user-attachments/assets/1cb38790-9db6-448e-9074-97da9111ff46)

**Comment by Vignesh025** [comment]
@devansh-dek That’s a good feature idea! Would you like to work on it?

**Comment by devansh-dek** [comment]
Sure i would love to. Please assign it to me.

**Comment by Vignesh025** [comment]
@devansh-dek, You can proceed. I'm assigning this to you!
