### ISSUE TITLE
[UI] Font color of home page is not good

### ISSUE THREAD

**Issue by nishtha-902** [VigneshDevHub/CampX#73]
**Description**
In home page, font color is not that much good, it must be adjusted according to background

**Current Behavior**
Due to white font it is not clearly visible
 
**Proposed Behavior**
Font color must be changed so that visibility is enhanced

**Related Issues**
Nav items are not visible due to over matched font color

**Comment by Vignesh025** [comment]
Hey @nishtha-902, someone else is currently working on the home page UI. Please feel free to explore the project and create new issues. We'd love your contributions!

**Comment by Vignesh025** [comment]
Hey @nishtha-902 , you may proceed with the issue as no one is currently working on it. Also, if possible, please update the UI of the homepage as well. Thanks!

**Comment by Vignesh025** [comment]
Hey @nishtha-902 , are you still working on this issue? If not, please let me know so I can assign it to someone else. Thanks!

**Comment by nilaygit-10721** [comment]
please assign me this issue

**Comment by Vignesh025** [comment]
Hey @nilaygit-10721 , This issue no longer exists.
