### ISSUE TITLE
[DOC] Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by Shariq2003** [VigneshDevHub/CampX#75]
## Description

We can add all the contributor's photos in Readme file as a token of appreciation for their work.

Please assign this to me.

![image](https://github.com/user-attachments/assets/24846984-f3d2-44a4-8d2b-2a5025d1ceb9)
Like this

**Affected Pages**:
- [X] README.md
- [ ] Installation Guide
- [ ] Configuration Guide
- [ ] Other (please specify)

## Type of Documentation Change

- [X] Update existing documentation
- [ ] Add new documentation
- [ ] Remove outdated or redundant documentation
- [ ] Other (please specify)

---

**Comment by Vignesh025** [comment]
I'm sorry, but someone else is already working on it. Let me know if you'd like to explore other opportunities to contribute!
