### ISSUE TITLE
[FEATURE] Addition of BackToTop Button

### ISSUE THREAD

**Issue by Shariq2003** [VigneshDevHub/CampX#76]
**Is your feature request related to a problem? Please describe.**
Addition of BackToTop Button should be there in website for better navigation from bottom to top in just single click

Please assign this to me.

**Comment by Sowmiyajayakumar** [comment]
Hey @Shariq2003, Please proceed, I’m assigning this issue to you. Thank you for taking the initiative.

**Comment by Vignesh025** [comment]
Hey @Shariq2003 , are you still working on this issue?

**Comment by Shariq2003** [comment]
Yes sir, upon review repo i have found that this repo uses a tech stack of ejs, and during setup of project I got stuck because of env requirements

**Comment by Vignesh025** [comment]
have you sorted out all the requirements and are you currently working on this issue? Let me know if you need any help!

**Comment by Shariq2003** [comment]
@Vignesh025 sir yes I need help in setting up the project

**Comment by Shariq2003** [comment]
.env required 

DB_URL="your_mongo_atlas_url"
CLOUDINARY_CLOUD_NAME="your_cloudinary_cloud_name"
CLOUDINARY_KEY="your_cloudinary_api_key"
CLOUDINARY_SECRET="your_cloudinary_api_secret"
MAPBOX_TOKEN="your_mapbox_token"

**Comment by Shariq2003** [comment]
That's why I have to create accounts on cloudinary, and mapbox

**Comment by Vignesh025** [comment]
Please read the ``INSTALLATION.md`` file, you'll know how to get those tokens.

> That's why I have to create accounts on cloudinary, and mapbox

Yes, you need to create accounts and get the token.

**Comment by Shariq2003** [comment]
> Please read the `INSTALLATION.md` file, you'll know how to get those tokens.
> 
> > That's why I have to create accounts on cloudinary, and mapbox
> 
> Yes, you need to create accounts and get the token.

Sure sir, could u please add the label of level for gssoc ext for this

**Comment by Shariq2003** [comment]
Sir level 1 ?

**Comment by Shariq2003** [comment]
Sir level 1?

**Comment by Vignesh025** [comment]
Make your pull request, depending upon the code and discussion with gssoc team, we'll decide the level.
the level in issue doesn't matter. the level in the pr matters

**Comment by Shariq2003** [comment]
> Make your pull request, depending upon the code and discussion with gssoc team, we'll decide the level. the level in issue doesn't matter. the level in the pr matters

okay sir

**Comment by Vignesh025** [comment]
Hey @Shariq2003 , why did you remove your assignment?

**Comment by Shariq2003** [comment]
Actually the mapbox account creation requires debit card, that's why I can't setup the project initialisation

**Comment by Vignesh025** [comment]
do you have a college mail id?

**Comment by Shariq2003** [comment]
Yes sir

**Comment by Vignesh025** [comment]
if you use that, it won't ask for any card details, it is free to use when you signup using college mail id

**Comment by adarshsingh0103** [comment]
@Shariq2003  Can you please! assign me to work on this issue.

**Comment by Sneharaj7645653** [comment]
Hey @Vignesh025 ,
I want to work on this issue. May you please assign it to me?

**Comment by Vignesh025** [comment]
> Hey @Vignesh025 , I want to work on this issue. May you please assign it to me?

Hey @Sneharaj7645653 , it's already done.

**Comment by Sneharaj7645653** [comment]
Oh, I see. Thank you.
