### ISSUE TITLE
[FEATURE] Add Search Functionality for Camping Locations

### ISSUE THREAD

**Issue by Dev-Rishav** [VigneshDevHub/CampX#77]
**Is your feature request related to a problem? Please describe.**
Yes, currently, if a user wants to search for a camping location, they must manually navigate the map, which can be time-consuming and inefficient.

**Describe the solution you'd like**
I propose adding a search bar that allows users to quickly find camping locations based on their preferences.

**Describe alternatives you've considered**
At this time, no alternatives have been considered.

**Additional context**
While there is a feature for fetching the nearest location, users may wish to explore camping spots elsewhere, making a search function essential for broader flexibility.

**Comment by Sowmiyajayakumar** [comment]
Hey @Dev-Rishav, That’s a great idea! Please proceed, I’m assigning this issue to you. Thank you for taking the initiative.
