### ISSUE TITLE
[FEATURE] : ADD hover animation for card component

### ISSUE THREAD

**Issue by samyak-aditya** [VigneshDevHub/CampX#79]
**Objective:** Enhance the user experience of the card component by implementing a hover animation that provides visual feedback when users interact with the card.
![Screenshot 2024-10-06 004232](https://github.com/user-attachments/assets/256e7eff-7b6f-467b-beba-94faecc8b7ba)

**Is your feature request related to a problem? Please describe.**

- The current card component lacks dynamic feedback, making it feel static and less engaging.
- The hover animation should include subtle scaling or shadow effects to create a sense of depth.
- The animation should be smooth and not distract from the overall usability of the component.

**Describe the solution you'd like**
Implementing this hover animation will improve the overall aesthetic of the card component and encourage user interaction.

**Additional context**
Hey @Vignesh025 Please assign me this Task with label "gssoc-ext", "hacktoberfest-accepted" and "level2"

**Comment by Ajitabh-Kalia** [comment]
can you assign me this issue?

**Comment by Vignesh025** [comment]
Hey @samyak-aditya , someone else is currently assigned to the UI of the campgrounds page. I'll check if they're still working on it. If not, I'll assign it to you.

**Comment by samyak-aditya** [comment]
Hey @Vignesh025 Thanks for the update 
Do let me know

**Comment by Vignesh025** [comment]
Hey @samyak-aditya , sorry but someone else is already working on it. Feel free to explore the project and raise any other issues you'd like to work on!
