### ISSUE TITLE
[UI] LOGO

### ISSUE THREAD

**Issue by shreyad2806** [VigneshDevHub/CampX#80]
**Description**
A clear and concise description of the proposed UI change. What part of the UI needs to be changed, and why?
I can add a personalized logo to make your website look more professional.

**Current Behavior**
Describe the current behavior or appearance of the UI that you want to change.

**Proposed Behavior**
Describe the new behavior or appearance. How should the UI look or function after the change?

**Screenshots**
If applicable, add screenshots or mockups to help explain the proposed change.

**Additional Context**
Add any other context, such as references to design guidelines, user feedback, or examples from other applications.

**Impact**
Explain the potential impact of this change. Will it improve usability, accessibility, performance, or visual appeal?

**Related Issues**
Link to any related issues, discussions, or feature requests that are relevant to this UI change.

**Comment by Vignesh025** [comment]
Yes @shreyad2806 , you can proceed! I'm assigning this you!
