### ISSUE TITLE
[FEATURE] Adding Password hide/show functionality

### ISSUE THREAD

**Issue by Sourabh782** [VigneshDevHub/CampX#82]
**Is your feature request related to a problem? Please describe.**
I wanted to add password show/hide functionality, making it easier for user to verify password

**Describe the solution you'd like**
i wanted to add a button so that user can view/hide his password

**Additional context**
![Screenshot 2024-10-06 111510](https://github.com/user-attachments/assets/229c2133-c898-4090-a333-261d1cc4c94f)

i want to work on it

**Comment by Vignesh025** [comment]
Hey @Sourabh782 , someone else is currently working on this feature. Please feel free to explore the project and create new issues. We'd love your contributions!
