### ISSUE TITLE
Add modal when user clicks logout

### ISSUE THREAD

**Issue by AyushSharma72** [VigneshDevHub/CampX#90]
**Is your feature request related to a problem? Please describe.**
when the user clicks logout button he directily logouts i want to add a modal which confirms user logout action

**Describe the solution you'd like**
add a modal for confirmation

![image](https://github.com/user-attachments/assets/7df9915c-0f8e-4740-b41c-87e306d35b42)

please assig this issue to me @Vignesh025

**Comment by Sowmiyajayakumar** [comment]
Hey @AyushSharma72, Please proceed, I’m assigning this issue to you. Thank you for taking the initiative.

**Comment by AyushSharma72** [comment]
> Hey @AyushSharma72, Please proceed, I’m assigning this issue to you. Thank you for taking the initiative.

you haven't added any level please dont forget to add the level in the pr before merging @Sowmiyajayakumar

**Comment by Vignesh025** [comment]
Hey @AyushSharma72 , are you still working on this issue? If not, please let me know so I can assign it to someone else. Thanks!
