### ISSUE TITLE
add loading when the user clicks login button

### ISSUE THREAD

**Issue by AyushSharma72** [VigneshDevHub/CampX#91]
**Is your feature request related to a problem? Please describe.**
i want to add a loading spinner when the user clicks login button 
it will give feedback to the user that the website is processing the user request

![image](https://github.com/user-attachments/assets/354f1cb0-8033-43c9-97c0-a8790185da4f)

please assign this issue to me @Vignesh025

**Comment by Sowmiyajayakumar** [comment]
Please proceed, I’m assigning this issue to you. Add the loader in register page as well. Thank you for taking the initiative.

**Comment by AyushSharma72** [comment]
you haven't added any level please dont forget to add the level in the pr before merging @Sowmiyajayakumar

**Comment by AyushSharma72** [comment]
> If you are not working on this issue, can I get assigned @Sowmiyajayakumar

Yes please you can work I am not working because the it was not running in my system when I started it there are some errors

**Comment by Vignesh025** [comment]
> If you are not working on this issue, can I get assigned @Sowmiyajayakumar

You can proceed, I'm assigning this to you!

**Comment by Vignesh025** [comment]
Hey @sameer-soni , are you still working on this issue? If not, please let me know so I can assign it to someone else. Thanks!
