### ISSUE TITLE
There is no proper handling of validation

### ISSUE THREAD

**Issue by venurockss** [VigneshDevHub/CampX#92]
Need to improve in the validation while registering to the website

**Comment by Sowmiyajayakumar** [comment]
Hey @venurockss, can you elaborate in detail on what validation you are proposing?

**Comment by venurockss** [comment]
while registration if the usertype the weak password then also it accepting as of now 
but in the improvementwe can display that error that the password should be strong enough.

**Comment by swarna-lohitt** [comment]
Hello @venurockss I've understood the issue and would like to work on it - Can you please assign it to me

**Comment by venurockss** [comment]
no @swarna-lohitt  i can handle it

**Comment by Vignesh025** [comment]
@venurockss , you can proceed. I'm assigning this to you.

**Comment by Vignesh025** [comment]
> Hello @Vignesh025 I've understood the issue and would like to work on it - Can you please assign it to me

Hey @swarna-lohitt ,

Thanks for your interest! However, the priority for assigning issues is given to the person who originally created it. I've already assigned this one, but feel free to explore the project and create new issues if you'd like to contribute!

**Comment by venurockss** [comment]
can please give the label of level 1

**Comment by venurockss** [comment]
@Vignesh025 can you give the proper labels for the issue

**Comment by Vignesh025** [comment]
@venurockss ,I can assign the appropriate labels only if you let me know which open-source program you're contributing from.
