### ISSUE TITLE
[FEATURE]:  improvement in the flash message 

### ISSUE THREAD

**Issue by venurockss** [VigneshDevHub/CampX#97]
Need to implement the custom flash message to the user after doing some thing like login and logout etc.

**Comment by Vignesh025** [comment]
Hey @venurockss ,

Custom flash messages are already available. Could you please elaborate on what specific messages you'd like to display and when you'd want them to appear?

Thanks!

**Comment by venurockss** [comment]
I mean that custom flash message is not designed properly

**Comment by Vignesh025** [comment]
@venurockss , you can proceed. I'm assigning this to you.
please specify whether you're part of any open source program. so that I can apply necessary labels

**Comment by venurockss** [comment]
@Vignesh025 add  appropriate labels gssoc-ext

**Comment by venurockss** [comment]
@Vignesh025 add appropriate labels for the issue 
Program is gssoc-ext
